# hechos/hechos_frase.py

from experta import Fact, Field

# ─────────────────────────────────────────────────────────────
# Hechos de entrada
# ─────────────────────────────────────────────────────────────

class EstadoEmocional(Fact):
    clasificacion      = Field(str, mandatory=True)
    nivel              = Field(str, mandatory=True)
    dias_consecutivos  = Field(int, mandatory=True)


# ─────────────────────────────────────────────────────────────
# Hechos derivados (declarados por el motor)
# ─────────────────────────────────────────────────────────────

class TipoFrase(Fact):
    tipo           = Field(str,  mandatory=True)
    mostrar_alerta = Field(bool, mandatory=True)


# ─────────────────────────────────────────────────────────────
# Base de conocimiento — pools de frases por tipo
# ─────────────────────────────────────────────────────────────

FRASES: dict[str, list[str]] = {

    # ── Emociones positivas — bajo ───────────────────────────
    "positiva_bajo": [
        "Incluso los momentos tranquilos tienen su valor. Hoy es un buen día para avanzar paso a paso.",
        "La alegría suave también es alegría. Aprovecha esta calma para enfocarte en lo que importa.",
        "Un estado positivo, aunque discreto, es el terreno ideal para aprender algo nuevo hoy.",
        "No hace falta estar eufórico para tener un gran día. Pequeños pasos cuentan.",
        "La tranquilidad que sientes hoy es una base sólida para construir algo valioso.",
        "Los días suaves también dejan huella. Aprovecha este momento para consolidar lo aprendido.",
        "Una chispa pequeña también puede encender algo grande. Hoy es un buen comienzo.",
        "Sentirte levemente bien ya es una victoria. No subestimes lo que puedes lograr desde aquí.",
        "La calma positiva es el punto ideal para tomar decisiones con claridad y sin prisa.",
        "No todos los días brillan igual, pero todos pueden avanzar. Hoy tienes el terreno a tu favor.",
        "Un estado de ánimo tranquilo y positivo es ideal para enfocarse en lo que realmente importa.",
        "Hoy no necesitas fuegos artificiales para avanzar. La constancia silenciosa también construye.",
        "Sentirte bien de manera discreta es igualmente valioso. Honra ese estado.",
        "La paz que sientes hoy es una invitación a reflexionar y agradecer lo que tienes.",
        "Incluso una leve sensación de bienestar puede ser el impulso que necesitas para dar el siguiente paso.",
        "Los momentos de calma positiva son perfectos para organizar tus ideas y prioridades.",
        "Hoy tu energía es suave pero real. Úsala con intención.",
        "No subestimes los días tranquilos. En ellos se fragua la constancia.",
        "Una actitud positiva discreta es más poderosa de lo que parece. Hoy lo tienes.",
        "Desde la calma también se avanza. A veces el camino más suave es el más efectivo.",
        "Hoy es un buen día para retomar algo pendiente con paciencia y enfoque.",
        "La alegría tranquila que sientes es una señal de que estás en equilibrio. Cuídala.",
        "Pequeñas dosis de bienestar, vividas con consciencia, suman más de lo que imaginas.",
        "Tu estado hoy es una invitación a avanzar sin presión. Aprovecha esa libertad.",
        "Sentirte levemente positivo/a es suficiente para hacer algo significativo hoy.",
        "La calma que acompaña tu bienestar de hoy es un recurso. No lo desperdicies.",
        "Hoy no tienes que conquistar el mundo. Con avanzar un poco ya es suficiente.",
        "Un estado suavemente positivo es el entorno perfecto para aprender algo nuevo.",
        "La tranquilidad positiva que sientes te permite ver con claridad lo que más importa.",
        "Hoy tu mente está en un buen lugar. Aprovecha esa claridad para algo que te sume.",
        "No hace falta una tormenta de emociones para vivir un día significativo. La calma también lo es.",
        "Tu bienestar de hoy, aunque discreto, merece ser reconocido y celebrado.",
        "Los días tranquilos son los que construyen la base de los grandes logros.",
        "Sentirte bien sin necesitar demostrarlo es una señal de madurez emocional.",
        "Hoy puedes avanzar a tu propio ritmo. No hay prisa, pero sí hay dirección.",
        "La levedad que sientes hoy es un regalo. Úsala para hacer algo que disfrutes.",
        "Un estado positivo suave es el escenario ideal para la creatividad y la reflexión.",
        "Hoy tienes el viento a tu favor, aunque sople despacio. Es suficiente para avanzar.",
        "Sentirte tranquilo/a y bien es una victoria cotidiana. No la pases por alto.",
        "Los días de calma positiva son los que más se agradecen cuando llegan los difíciles.",
        "Tu equilibrio emocional de hoy es una plataforma sólida. Construye desde aquí.",
        "Hoy puedes hacer algo pequeño pero significativo. Eso siempre suma.",
        "La sutileza de tu bienestar de hoy no le resta valor. Todo lo contrario.",
        "Avanzar despacio también es avanzar. Hoy tienes la calma para hacerlo bien.",
        "Tu estado de ánimo hoy invita a la reflexión y al enfoque. Aprovéchalo.",
        "No todo tiene que ser intenso para ser valioso. Hoy lo suave también cuenta.",
        "Sentirte así de tranquilo/a y bien es exactamente lo que necesitas para seguir adelante.",
        "La paz interior que experimentas hoy es un activo que pocas personas tienen. Valórala.",
        "Hoy es un buen día para agradecer, enfocarse y avanzar con serenidad.",
        "Incluso desde la calma más discreta, puedes dar pasos que marquen la diferencia.",
    ],

    # ── Emociones positivas — medio ──────────────────────────
    "positiva_medio": [
        "Tu energía de hoy es un regalo. Úsala para avanzar en algo que te apasione.",
        "Cuando te sientes bien, aprender fluye con más facilidad. ¡Aprovecha el momento!",
        "Un buen estado de ánimo multiplica tu capacidad. Hoy tienes mucho por dar.",
        "Estás en un momento ideal para retomar algo pendiente con entusiasmo.",
        "Este nivel de energía es perfecto para enfrentar retos con confianza.",
        "Tu bienestar de hoy es combustible para tus metas. No lo desperdicies.",
        "Sientes equilibrio y energía. Es el momento ideal para dar ese paso que has estado posponiendo.",
        "Los días así son oportunidades disfrazadas de rutina. Aprovecha cada momento.",
        "Tu estado de ánimo hoy es un activo. Invierte esa energía en lo que realmente importa.",
        "Cuando estás bien, el mundo responde diferente. Sal a él con intención hoy.",
        "Hoy tienes la combinación perfecta de calma y energía. Úsala sabiamente.",
        "Tu bienestar de hoy es una señal de que vas por buen camino. Sigue así.",
        "Sentirte bien con esta intensidad te abre puertas. ¿Cuál quieres cruzar hoy?",
        "El entusiasmo moderado es el más sostenible. Hoy lo tienes. Aprovéchalo.",
        "Tu energía de hoy no es casualidad. Es el resultado de tu esfuerzo. Celébralo.",
        "Un buen estado de ánimo es contagioso. Comparte tu energía con quienes te rodean.",
        "Hoy estás en sintonía contigo mismo/a. Es un buen momento para tomar decisiones importantes.",
        "La energía que sientes hoy es suficiente para mover lo que necesita moverse.",
        "Sentirte así es una invitación a actuar. ¿Qué has estado postergando?",
        "Tu bienestar de hoy merece ser honrado con acciones que te acerquen a tus metas.",
        "Hoy tienes el impulso necesario para avanzar en lo que más importa.",
        "Un estado de ánimo positivo y equilibrado es el mejor aliado para aprender.",
        "Aprovecha esta energía para conectar con algo que te inspire y te mueva.",
        "Tu entusiasmo de hoy es una herramienta poderosa. Úsala con propósito.",
        "Sentirte bien a este nivel te permite dar lo mejor de ti. Hoy es ese día.",
        "La motivación que sientes hoy es real. Actúa antes de que se disipe.",
        "Hoy tu mente y tu corazón están alineados. Es el momento ideal para crear.",
        "Un buen estado emocional abre la puerta a mejores relaciones, decisiones y aprendizajes.",
        "Hoy tienes energía de sobra para enfrentar lo que se ponga en tu camino.",
        "Tu bienestar de hoy es el resultado de pequeñas decisiones correctas. Reconócelas.",
        "Sentirte así de bien es una oportunidad para ser la mejor versión de ti mismo/a.",
        "La energía positiva que traes hoy puede transformar cualquier tarea en algo significativo.",
        "Hoy estás en tu elemento. Aprovecha ese estado para avanzar con determinación.",
        "Tu motivación de hoy es un recurso valioso. Inviértela en lo que más te importa.",
        "Cuando el ánimo acompaña, los obstáculos se achican. Hoy tienes ese ánimo.",
        "Un estado positivo sostenido construye confianza. Hoy estás abonando ese terreno.",
        "Sientes bienestar y claridad. Es la combinación perfecta para tomar acción.",
        "Tu energía de hoy es más que suficiente para hacer algo memorable.",
        "Hoy puedes avanzar sin esfuerzo extra. El ánimo está de tu lado.",
        "Sentirte así te recuerda de lo que eres capaz. No lo olvides cuando vengan días difíciles.",
        "Tu estado emocional de hoy es una plataforma de lanzamiento. ¿A dónde quieres ir?",
        "La vitalidad que sientes hoy es un regalo. Compártela, exprésala, úsala.",
        "Hoy tienes todo lo necesario para dar un paso importante. No lo postergues.",
        "Un ánimo positivo y equilibrado hace que todo fluya mejor. Hoy lo tienes.",
        "Tu bienestar de hoy no es una casualidad. Es el fruto de tu cuidado personal.",
        "Sentirte bien te da perspectiva. Úsala para ver el panorama completo.",
        "Hoy es un buen día para conectar, crear, aprender y avanzar. Tienes el estado para todo.",
        "La energía que llevas hoy puede hacer que lo difícil se sienta posible.",
        "Tu entusiasmo de hoy es genuino y poderoso. No lo subestimes.",
        "Aprovecha este estado de bienestar para sembrar hábitos que quieras mantener.",
    ],

    # ── Emociones positivas — alto ───────────────────────────
    "positiva_alto": [
        "¡Tu energía hoy es contagiosa! Aprovéchala para avanzar en lo que más importa.",
        "Días así son para recordar. Haz algo hoy que tu yo futuro agradezca.",
        "Cuando la motivación está al máximo, los límites se vuelven invitaciones. ¡Adelante!",
        "Este nivel de energía positiva es tuyo. Úsalo con intención y disfruta el proceso.",
        "Hoy eres imparable. Canaliza esa fuerza hacia algo que te llene de orgullo.",
        "La euforia bien dirigida mueve montañas. ¿Qué montaña quieres mover hoy?",
        "Este es el tipo de día que recuerdas cuando los tiempos se ponen difíciles. Vívelo plenamente.",
        "Tu entusiasmo de hoy puede contagiar a quienes te rodean. Comparte esa energía.",
        "Estás en tu mejor versión hoy. No te conformes con poco cuando puedes dar mucho.",
        "La energía que sientes es real y poderosa. Úsala para crear algo que valga la pena.",
        "Hoy tu potencial está al máximo. Es el momento de ir por lo que siempre has querido.",
        "Una energía así no llega todos los días. Aprovéchala hasta el último momento.",
        "Tu vitalidad hoy es extraordinaria. Dirige esa fuerza con propósito y claridad.",
        "Cuando la energía es tan alta, las posibilidades se multiplican. ¿Cuál vas a elegir?",
        "Hoy sientes que puedes con todo, y probablemente tengas razón. ¡Demuéstratelo!",
        "Tu estado de ánimo hoy es una ventaja competitiva. Úsala bien.",
        "La intensidad positiva que sientes hoy es un motor poderoso. No dejes que se desperdicie.",
        "Días como hoy te recuerdan por qué vale la pena el esfuerzo diario. Aprovéchalo.",
        "Hoy tienes la energía para hacer lo que normalmente se siente difícil. Úsala.",
        "Tu entusiasmo desbordante de hoy merece ser encauzado hacia algo significativo.",
        "La motivación a tope es un estado privilegiado. Actúa mientras la tienes.",
        "Hoy puedes ser la versión más brillante de ti mismo/a. No te quedes corto/a.",
        "Con esta energía, cualquier meta se siente alcanzable. ¿Cuál vas a perseguir hoy?",
        "Tu estado emocional hoy es extraordinario. Merece acciones extraordinarias.",
        "La alegría intensa que sientes es una fuerza. Dirígela hacia lo que más valoras.",
        "Hoy tienes el empuje para romper límites que creías fijos. Ve por ello.",
        "Tu energía al máximo es un recurso escaso y valioso. Inviértela sabiamente.",
        "Días así no se olvidan. Haz algo hoy que valga la pena recordar.",
        "Con esta motivación, los obstáculos se convierten en escalones. Sube.",
        "Tu vitalidad de hoy es contagiosa. Compártela con quien la necesite.",
        "Hoy estás en llamas. Canaliza esa energía con propósito y determinación.",
        "La intensidad de tu bienestar hoy es una señal de que algo grande es posible.",
        "No desperdicies esta energía en lo trivial. Hoy apunta a lo que realmente importa.",
        "Tu entusiasmo de hoy puede cambiar el rumbo de algo importante. ¡Actúa!",
        "Cuando te sientes así de bien, el mundo entero parece posible. Aprovecha esa perspectiva.",
        "Hoy tienes la energía para hacer, crear, conectar y avanzar. No te quedes quieto/a.",
        "La euforia positiva que sientes es una oportunidad. No la dejes pasar sin usarla.",
        "Tu estado hoy es excepcional. Úsalo para hacer algo que normalmente te costaría más.",
        "Días de máxima energía son días para atreverse. ¿Qué vas a atreverse a hacer hoy?",
        "Hoy tu mejor versión está disponible. Ponla en acción.",
        "Con esta energía, no hay tarea demasiado grande ni sueño demasiado ambicioso.",
        "Tu motivación hoy es un regalo. Trátala como tal y no la desperdicies.",
        "Hoy todo fluye a tu favor. Aprovecha ese impulso para avanzar con decisión.",
        "La intensidad positiva de hoy es tuya. Nadie más puede aprovecharla por ti.",
        "Tu energía al máximo merece metas al máximo. ¿Cuál es la tuya hoy?",
        "Hoy sientes que nada puede detenerte. Esa confianza es tu mayor fortaleza.",
        "La alegría intensa que experimentas hoy es una de las mejores sensaciones. Vívela.",
        "Tu vitalidad de hoy habla por sí sola. Deja que tus acciones la acompañen.",
        "Una energía tan alta como la de hoy merece ser recordada. Haz algo memorable.",
        "Hoy eres la mejor versión de ti mismo/a. Actúa en consecuencia.",
    ],

    # ── Emociones neutras — bajo ─────────────────────────────
    "neutra_bajo": [
        "La calma es el punto de partida ideal para aprender algo nuevo hoy.",
        "No siempre hay que sentir mucho para avanzar. La constancia supera al entusiasmo.",
        "Un día tranquilo es una oportunidad para consolidar lo que ya sabes.",
        "La neutralidad también es equilibrio. Hoy puedes avanzar sin prisa y sin pausa.",
        "No necesitas emoción desbordante para ser productivo. La calma también construye.",
        "Los días tranquilos son los que forjan el hábito. Hoy suma aunque no lo parezca.",
        "Sentirte neutro no es malo. Es un espacio limpio para decidir con cabeza fría.",
        "La ausencia de ruido emocional es un lujo. Aprovéchalo para enfocarte.",
        "Hoy puedes avanzar sin que nada te frene. A veces la calma es el mejor viento.",
        "Un estado neutro y sereno puede ser más productivo que uno lleno de distracciones.",
        "La neutralidad emocional te permite ver las cosas tal como son, sin filtros.",
        "Hoy no hay tormentas internas. Es el momento ideal para construir con paciencia.",
        "Un día sin grandes emociones también puede ser un gran día. Depende de ti.",
        "La quietud que sientes hoy es una invitación a la reflexión y al enfoque.",
        "Sentirte neutro/a es una señal de que estás en un punto de equilibrio. Cuídalo.",
        "Desde la calma discreta también se pueden hacer cosas importantes.",
        "Hoy tu mente está limpia de interferencias. Es el momento para trabajar con claridad.",
        "No todo tiene que sentirse intenso para ser valioso. La calma también construye.",
        "La tranquilidad que experimentas hoy es una plataforma sólida. Úsala.",
        "Los días neutros son los más subestimados y los más productivos.",
        "Hoy puedes avanzar sin el peso de las emociones intensas. Aprovecha esa ligereza.",
        "La serenidad discreta que sientes hoy te permite ver con claridad.",
        "Un estado neutro es el lienzo en blanco sobre el que puedes pintar lo que quieras.",
        "Hoy no tienes ni demasiado ni poco. Tienes exactamente lo que necesitas.",
        "La calma que sientes hoy es valiosa. No la interrumpas innecesariamente.",
        "Desde la neutralidad puedes elegir con libertad hacia dónde dirigir tu energía.",
        "Hoy no hay nada que te desvíe del camino. Es el momento de avanzar recto.",
        "La estabilidad emocional que sientes hoy es un activo. Aprovéchalo.",
        "Un día tranquilo es una oportunidad para hacer lo que normalmente se pospone.",
        "Sentirte neutro/a es estar en el centro del equilibrio. Desde ahí puedes ir a cualquier lugar.",
        "La calma de hoy no es vacío, es espacio. Llénalos con lo que realmente importa.",
        "Hoy tienes claridad sin ruido. Es el estado ideal para tomar buenas decisiones.",
        "La tranquilidad que experimentas hoy es suficiente para hacer algo significativo.",
        "Un estado neutro bien aprovechado puede producir resultados sorprendentes.",
        "Hoy no hay nada que te distraiga de lo esencial. Aprovecha esa claridad.",
        "La serenidad de hoy es una herramienta poderosa si sabes usarla.",
        "Desde la calma también se llega lejos. Hoy tienes esa calma.",
        "Un día sin grandes emociones es un día sin grandes distracciones. Aprovéchalo.",
        "La neutralidad emocional de hoy te da una perspectiva objetiva y valiosa.",
        "Hoy puedes avanzar sin el ruido de las emociones intensas. Eso es un regalo.",
        "La tranquilidad que sientes hoy no es ausencia de vida, es presencia plena.",
        "Sentirte neutro/a y en calma es uno de los estados más productivos que existen.",
        "Hoy tu energía está disponible y sin interferencias. Dirígela bien.",
        "La calma que traes hoy es suficiente para hacer lo que necesitas hacer.",
        "Un estado neutro y sereno es el terreno fértil para la concentración profunda.",
        "Hoy tienes equilibrio. Desde ahí puedes construir lo que quieras.",
        "La tranquilidad de hoy es una oportunidad para hacer algo con calidad y enfoque.",
        "Sentirte así de sereno/a es un estado que muchos buscan. Hoy lo tienes.",
        "La neutralidad de hoy te libera de extremos. Aprovecha esa libertad.",
        "Hoy puedes ser constante sin esfuerzo extra. La calma hace eso posible.",
    ],

    # ── Emociones neutras — medio ────────────────────────────
    "neutra_medio": [
        "Estás en un estado de equilibrio. Es un buen momento para revisar tus metas.",
        "La serenidad que sientes hoy es una buena base para tomar decisiones con claridad.",
        "Un estado neutro te permite ver las cosas con objetividad. Aprovecha esa claridad.",
        "No todo día tiene que ser intenso. Los días tranquilos construyen el hábito.",
        "Desde la neutralidad puedes observar sin juzgar. Eso es una habilidad valiosa.",
        "El equilibrio emocional que sientes hoy es una herramienta. Úsala bien.",
        "La serenidad es la plataforma perfecta para pensar con profundidad.",
        "Hoy tu mente está despejada. Es el momento para analizar y planificar.",
        "Desde la calma se ven más lejos los caminos. Tómate un momento para mirar adelante.",
        "El estado neutro es el centro del péndulo. Es desde aquí que puedes elegir hacia dónde moverte.",
        "Tu equilibrio de hoy es una señal de salud emocional. Reconócelo y celébralo.",
        "La calma que sientes no es indiferencia, es estabilidad. Hay una gran diferencia.",
        "Hoy tienes la distancia emocional necesaria para ver las cosas con perspectiva.",
        "Un estado equilibrado como el de hoy es ideal para resolver problemas con claridad.",
        "La neutralidad que experimentas te permite escuchar mejor a los demás y a ti mismo/a.",
        "Hoy puedes pensar con claridad y actuar con coherencia. Aprovecha ese estado.",
        "El equilibrio emocional es una de las habilidades más valiosas. Hoy la tienes.",
        "Desde la serenidad se toman las mejores decisiones. Hoy tienes esa serenidad.",
        "Tu estado de hoy es una ventaja. No todos logran este nivel de equilibrio.",
        "La calma que sientes hoy te permite conectar con lo que realmente importa.",
        "Un estado neutro y equilibrado es el mejor punto de partida para cualquier tarea.",
        "Hoy puedes ser objetivo/a y claro/a. Eso es más valioso de lo que parece.",
        "La estabilidad emocional de hoy es un recurso. Inviértelo en algo que sume.",
        "Sentirte en equilibrio te da una perspectiva limpia. Úsala para tomar buenas decisiones.",
        "Hoy no hay nada que distorsione tu percepción. Aprovecha esa claridad.",
        "La serenidad equilibrada que sientes hoy es perfecta para reflexionar y planificar.",
        "Tu calma de hoy es una fortaleza silenciosa. Reconócela.",
        "Desde el equilibrio puedes ver tanto las oportunidades como los riesgos con claridad.",
        "Hoy tienes una mente tranquila y dispuesta. Úsala para hacer algo que valga la pena.",
        "La neutralidad que sientes no es falta de pasión, es claridad mental. Aprovéchala.",
        "Un estado equilibrado como el de hoy facilita el aprendizaje y la concentración.",
        "Hoy puedes abordar cualquier tarea con la mente limpia y el corazón tranquilo.",
        "La calma que experimentas hoy es el estado ideal para la creatividad sostenida.",
        "Tu equilibrio emocional de hoy te permite dar lo mejor de ti sin agotarte.",
        "Sentirte así de tranquilo/a es una señal de que estás en el camino correcto.",
        "La serenidad de hoy es una plataforma sólida. Construye algo importante desde aquí.",
        "Hoy tienes equilibrio interior y claridad exterior. Es la combinación perfecta.",
        "Un estado neutro y estable como el de hoy es más valioso de lo que parece.",
        "La calma que sientes te permite escuchar tu intuición con más claridad.",
        "Hoy puedes avanzar con constancia y sin drama. Eso es poderoso.",
        "Tu estado de equilibrio hoy es una señal de madurez emocional. Recónocela.",
        "La tranquilidad que sientes te da libertad para elegir cómo reaccionar ante cada situación.",
        "Hoy tienes la calma necesaria para hacer las cosas bien, sin prisa y sin descuido.",
        "Un estado neutro equilibrado es el terreno perfecto para la concentración profunda.",
        "La serenidad que experimentas hoy es un activo. No la subestimes.",
        "Hoy puedes ser la versión más ecuánime de ti mismo/a. Aprovecha esa capacidad.",
        "Tu equilibrio de hoy te permite ver los problemas como lo que son, no como tragedias.",
        "La calma que sientes hoy es una señal de que tu trabajo interior está dando frutos.",
        "Sentirte en equilibrio es una de las mejores sensaciones posibles. Hoy la tienes.",
        "Tu estado neutro y equilibrado de hoy es el punto de partida ideal para cualquier cosa.",
    ],

    # ── Emociones neutras — alto ─────────────────────────────
    "neutra_alto": [
        "Tu calma hoy es notable. Ese equilibrio interno es una fortaleza real.",
        "Sentirte estable es más valioso de lo que parece. Desde aquí puedes construir mucho.",
        "La tranquilidad profunda es un estado privilegiado. Úsala para reflexionar y planificar.",
        "Estás centrado/a. Ese es el mejor punto de partida para cualquier cosa que quieras lograr hoy.",
        "Una serenidad tan sólida es difícil de alcanzar. Hoy la tienes. Aprovéchala al máximo.",
        "Tu equilibrio de hoy habla de trabajo interno. Eso se nota y se valora.",
        "Desde esta calma profunda puedes tomar decisiones que realmente importan.",
        "La estabilidad que sientes hoy es tu mayor recurso. No la subestimes.",
        "Pocas cosas son tan poderosas como una mente tranquila y clara. Hoy la tienes.",
        "Este estado de paz profunda es un regalo. Dedica tiempo a algo que realmente valoras.",
        "Tu serenidad de hoy es extraordinaria. Pocos logran este nivel de equilibrio interno.",
        "La paz profunda que experimentas hoy es el resultado de un trabajo interno real.",
        "Hoy tu calma es tan profunda que puedes abordar cualquier desafío con ecuanimidad.",
        "Una tranquilidad tan intensa como la de hoy es un estado que merece ser honrado.",
        "Tu equilibrio interno de hoy es notable. Úsalo para hacer algo realmente significativo.",
        "La serenidad profunda que sientes hoy te da una claridad excepcional.",
        "Hoy tienes una paz interior que es difícil de conseguir. Aprovéchala plenamente.",
        "Tu calma de hoy no es pasividad, es poder. Dirígelo con propósito.",
        "Un estado de serenidad tan profundo como el de hoy es una oportunidad excepcional.",
        "La estabilidad emocional profunda que sientes hoy es una ventaja enorme.",
        "Hoy tu mente está en un estado de claridad excepcional. Úsala para lo más importante.",
        "La paz interior que experimentas hoy es la base desde la que se construyen grandes cosas.",
        "Tu serenidad de hoy es una fortaleza real. No todos llegan a este nivel de equilibrio.",
        "Desde una calma tan profunda como la de hoy, todo parece posible y alcanzable.",
        "Tu estado de ecuanimidad hoy es extraordinario. Honralo con acciones de igual calidad.",
        "La tranquilidad profunda que sientes hoy te permite ver con una claridad excepcional.",
        "Hoy tienes un nivel de equilibrio interior que es difícil de lograr. Celébralo.",
        "Tu calma profunda de hoy es una herramienta poderosa. Úsala con intención.",
        "Una serenidad tan intensa como la de hoy abre puertas que normalmente están cerradas.",
        "Hoy tu equilibrio interior es tu mayor fortaleza. Actúa desde ese lugar.",
        "La paz profunda que experimentas hoy es una señal de crecimiento personal real.",
        "Tu serenidad de hoy es excepcional. Merece ser usada en algo que esté a su altura.",
        "Desde esta calma tan profunda puedes hacer cosas que normalmente requieren mucho más esfuerzo.",
        "Hoy tienes una claridad interior extraordinaria. Úsala para tomar decisiones importantes.",
        "Tu equilibrio profundo de hoy es una de tus mayores fortalezas. Reconócela.",
        "La tranquilidad intensa que sientes hoy es el estado ideal para el trabajo profundo.",
        "Hoy tu paz interior es tan sólida que nada puede desestabilizarte fácilmente.",
        "Una calma tan profunda como la de hoy es un estado privilegiado. Aprovéchala.",
        "Tu serenidad de hoy te da una perspectiva que va más allá de lo cotidiano.",
        "Hoy tienes una estabilidad emocional extraordinaria. Úsala para algo extraordinario.",
        "La paz interior profunda que experimentas hoy es una de las mejores bases posibles.",
        "Tu calma de hoy es una señal de que has trabajado en ti mismo/a. Eso vale mucho.",
        "Desde una serenidad tan profunda, los problemas se ven con una claridad excepcional.",
        "Hoy tu equilibrio interior es tan sólido que puedes ayudar a otros desde ese lugar.",
        "La tranquilidad profunda que sientes hoy es un recurso escaso y valioso.",
        "Tu estado de paz de hoy te permite conectar con lo más esencial de ti mismo/a.",
        "Una calma tan intensa como la de hoy merece ser aprovechada en algo que importe.",
        "Hoy tienes una serenidad que pocos logran. Úsala para avanzar en lo que más importa.",
        "Tu equilibrio profundo de hoy es tu mayor activo. Inviértelo sabiamente.",
        "La paz interior que experimentas hoy es una señal de que estás en el camino correcto.",
    ],

    # ── Emociones negativas — bajo ───────────────────────────
    "negativa_bajo": [
        "No todos los días se sienten perfectos, y está bien. Date un momento para respirar.",
        "Las emociones difíciles también tienen algo que enseñarnos. Escúchate con amabilidad.",
        "Incluso en días grises, pequeñas acciones marcan la diferencia. Un paso es suficiente.",
        "Está bien no estar bien del todo. La autocompasión también es parte del aprendizaje.",
        "Los días difíciles también pasan. Hoy solo necesitas llegar al final del día.",
        "Sentirte así a veces es completamente normal. No te exijas más de lo que puedes dar hoy.",
        "Incluso una pequeña acción positiva puede cambiar el rumbo del día.",
        "No tienes que resolver todo hoy. A veces basta con cuidarte un poco.",
        "Los días difíciles son parte del camino, no el camino entero.",
        "Permítete sentir sin juzgarte. Las emociones son información, no debilidades.",
        "Hoy no tienes que ser tu mejor versión. Con ser tú mismo/a es suficiente.",
        "Un día difícil no define tu trayectoria. Es solo un día.",
        "Date permiso de tener un día menos brillante. No pasa nada.",
        "Las emociones difíciles son visitantes temporales. No les abras la puerta de par en par.",
        "Hoy puedes avanzar despacio. No tienes que correr.",
        "Reconocer que no te sientes bien ya es un acto de honestidad valioso.",
        "No tienes que fingir que estás bien si no lo estás. La autenticidad también es fortaleza.",
        "Un día con emociones difíciles también puede tener momentos de calma. Búscalos.",
        "Lo que sientes hoy es válido. No lo minimices ni lo exageres.",
        "Hoy puedes ser gentil contigo mismo/a. Eso también es productivo.",
        "Las emociones incómodas a veces son señales de que algo necesita atención. Escúchalas.",
        "No hace falta estar bien para hacer algo pequeño y significativo hoy.",
        "Hoy puedes darte el permiso de no rendir al cien. Mañana es otro día.",
        "Un estado emocional difícil no cancela tu valor como persona.",
        "Sentirte así hoy no significa que mañana vaya a ser igual.",
        "Las emociones difíciles son parte de la experiencia humana. No estás solo/a en esto.",
        "Hoy basta con respirar, avanzar poco a poco y llegar al final del día.",
        "No tienes que superar todo de golpe. Un paso a la vez es suficiente.",
        "Lo que sientes hoy tiene valor aunque sea incómodo. Escúchalo con curiosidad.",
        "Hoy puedes ser compasivo/a contigo mismo/a. Te lo mereces.",
        "Un día difícil es una oportunidad para practicar la resiliencia. Sin prisa.",
        "Sentirte así no es un fracaso. Es parte de ser humano/a.",
        "Hoy puedes hacer lo mínimo necesario y eso está perfectamente bien.",
        "Las emociones difíciles también pasan. Confía en eso.",
        "No tienes que estar siempre bien. Hoy puedes simplemente estar.",
        "Un estado emocional difícil es temporal. Esto también va a cambiar.",
        "Hoy puedes cuidarte sin culpa. El autocuidado no es egoísmo.",
        "Sentirte así a veces es una señal de que eres humano/a y estás vivo/a.",
        "No te juzgues por cómo te sientes hoy. Las emociones no se eligen.",
        "Hoy puedes ir despacio. La tortuga también llega a la meta.",
        "Un día difícil bien atravesado construye fortaleza. Estás haciéndolo.",
        "Lo que sientes hoy merece ser reconocido, no ignorado ni amplificado.",
        "Hoy puedes darte un descanso sin culpa. Lo necesitas y lo mereces.",
        "Las emociones difíciles a veces son el precio de estar completamente vivo/a.",
        "No tienes que solucionar hoy lo que no se rompió hoy.",
        "Sentirte así es válido. Y también es temporal. Las dos cosas son ciertas.",
        "Hoy puedes simplemente respirar y dejar que el día pase.",
        "Un estado emocional difícil no te define. Es solo cómo te sientes hoy.",
        "Lo más valiente que puedes hacer hoy es cuidarte sin juzgarte.",
        "Hoy no tienes que ser fuerte. Solo tienes que ser honesto/a contigo mismo/a.",
    ],

    # ── Emociones negativas — medio ──────────────────────────
    "negativa_medio": [
        "Sentir esto con intensidad media es una señal de que algo merece tu atención. ¿Qué necesitas hoy?",
        "No tienes que resolver todo hoy. A veces descansar ya es avanzar.",
        "Las emociones difíciles son temporales, aunque no lo parezca en el momento.",
        "Date permiso de sentir. Ignorar las emociones difíciles no las hace desaparecer.",
        "Lo que sientes hoy tiene valor. Escúchalo en lugar de huir de ello.",
        "Reconocer una emoción difícil ya es un acto de valentía. Vas bien.",
        "No tienes que estar bien para seguir adelante. Avanza a tu ritmo.",
        "Las emociones incómodas son invitaciones a mirar hacia adentro. ¿Qué te están diciendo?",
        "Hoy puede ser difícil, pero no definitivo. Mañana empieza otra oportunidad.",
        "Cada vez que te permites sentir y sigues adelante, te vuelves más fuerte.",
        "Lo que sientes hoy es importante. No lo minimices con frases de superación fácil.",
        "Permitirte sentir esto con honestidad es el primer paso para manejarlo.",
        "No tienes que disimular lo que sientes. La autenticidad también es una forma de avanzar.",
        "Lo que estás experimentando hoy merece atención y cuidado, no ignorarse.",
        "Hoy puedes hacer menos y cuidarte más. Eso también es productivo.",
        "Las emociones difíciles a esta intensidad son señales de que algo necesita espacio.",
        "No tienes que superar esto solo/a. Hay personas dispuestas a acompañarte.",
        "Lo que sientes hoy tiene peso. Reconócelo y busca la manera de aliviarlo.",
        "Hoy puedes pedir ayuda. No es señal de debilidad, es señal de inteligencia emocional.",
        "Las emociones difíciles que sientes hoy merecen ser escuchadas, no silenciadas.",
        "Hoy puede ser un día para descansar, reflexionar y darte el espacio que necesitas.",
        "Lo que sientes con esta intensidad es real y válido. No lo ignores.",
        "No tienes que fingir que estás bien cuando no lo estás. La honestidad es más sana.",
        "Hoy puedes ser compasivo/a contigo mismo/a. Te lo has ganado.",
        "Las emociones difíciles también tienen un principio y un fin. Este también pasará.",
        "No tienes que resolverlo todo hoy. A veces lo más valiente es descansar.",
        "Lo que sientes hoy merece ser atendido con cuidado y sin juicio.",
        "Hoy es un día para cuidarte, no para exigirte. Date ese permiso.",
        "Las emociones incómodas que sientes son temporales, aunque se sientan permanentes.",
        "No estás solo/a en lo que sientes. Muchas personas han estado en este lugar.",
        "Hoy puedes ir más despacio. No hay ninguna regla que diga que tienes que correr.",
        "Lo que sientes con esta intensidad merece ser expresado, no guardado.",
        "Hoy es un buen día para hablar con alguien de confianza sobre cómo te sientes.",
        "Las emociones difíciles que atraviesas hoy son parte del proceso. Confía en él.",
        "No tienes que estar en tu mejor momento para merecer cuidado y apoyo.",
        "Hoy puedes poner las metas en pausa y priorizar tu bienestar. Está bien.",
        "Lo que sientes hoy es una señal de que algo en tu vida merece atención.",
        "No tienes que superar esto de golpe. Un día a la vez es suficiente.",
        "Las emociones difíciles a esta intensidad son una invitación a buscar apoyo.",
        "Hoy puedes darte permiso de no estar bien. No tiene que haber razón suficiente.",
        "Lo que sientes merece espacio y tiempo. No te apresures a superarlo.",
        "No tienes que cargar esto solo/a. Buscar apoyo es un acto de valentía.",
        "Hoy puede ser un día difícil, pero también puede ser el día en que pidas ayuda.",
        "Las emociones difíciles que sientes hoy son reales y merecen atención real.",
        "No tienes que minimizar lo que sientes para que los demás se sientan cómodos.",
        "Hoy puedes cuidarte sin justificarte. Tu bienestar no necesita justificación.",
        "Lo que sientes con esta intensidad merece ser atendido, no ignorado.",
        "Hoy es un buen día para respirar profundo y darte el espacio que necesitas.",
        "Las emociones difíciles a veces son el cuerpo y la mente pidiendo descanso. Escúchalos.",
        "No tienes que superar todo para merecer apoyo. Solo tienes que pedirlo.",
    ],

    # ── Emociones negativas — alto ───────────────────────────
    "negativa_alto": [
        "Sentir esto con tanta intensidad es agotador. Permítete pausar antes de continuar.",
        "No tienes que cargar esto solo/a. Hablar con alguien de confianza puede aliviar mucho.",
        "Las emociones intensas son señales, no sentencias. Hoy puedes tomarte un respiro.",
        "Está bien pedir ayuda. Buscar apoyo es un acto de valentía, no de debilidad.",
        "Cuando la intensidad emocional es alta, el cuerpo también lo siente. Cuídate físicamente hoy.",
        "No te exijas rendimiento cuando estás en el límite. Hoy el autocuidado es la tarea.",
        "Lo que sientes es real y válido. Y también es temporal. Esto va a cambiar.",
        "Días así exigen cuidado extra. No te descuides.",
        "La intensidad de lo que sientes hoy es una señal clara de que necesitas apoyo.",
        "No tienes que atravesar esto sin ayuda. Hay personas dispuestas a acompañarte.",
        "Lo que sientes con esta intensidad merece atención urgente y cuidado real.",
        "Hoy no es el día para exigirte. Es el día para cuidarte.",
        "La intensidad emocional que experimentas hoy es agotadora. Date el descanso que necesitas.",
        "No tienes que poder con todo. Hoy está bien pedir ayuda.",
        "Lo que sientes con tanta intensidad es una señal de que algo importante necesita atención.",
        "Hoy más que nunca, tu bienestar es la prioridad. Todo lo demás puede esperar.",
        "La intensidad de tus emociones hoy merece ser tomada en serio, por ti y por los demás.",
        "No estás obligado/a a gestionar esto solo/a. Busca apoyo hoy.",
        "Lo que sientes con esta fuerza es una señal de que necesitas apoyo y descanso.",
        "Hoy tu tarea principal es cuidarte. Nada más es más urgente que eso.",
        "La intensidad emocional que atraviesas hoy requiere gentileza, no exigencia.",
        "No tienes que estar bien para merecer apoyo. Precisamente cuando no estás bien, más lo mereces.",
        "Lo que sientes hoy con tanta intensidad es real. No lo minimices ni lo ignores.",
        "Hoy puede ser uno de los días más difíciles, y eso hace que el apoyo sea más necesario.",
        "La intensidad de lo que sientes es una señal de que mereces atención y cuidado especial.",
        "No tienes que resolver esto solo/a. Pedir ayuda es la decisión más inteligente que puedes tomar hoy.",
        "Lo que estás atravesando con esta intensidad merece apoyo profesional si lo necesitas.",
        "Hoy es el día para bajar la guardia y dejar que alguien te ayude.",
        "La intensidad emocional que sientes hoy es válida y merece ser atendida con seriedad.",
        "No tienes que ser fuerte hoy. Puedes ser vulnerable y pedir lo que necesitas.",
        "Lo que sientes con tanta fuerza hoy es una señal de que algo importante necesita cambiar.",
        "Hoy tu bienestar no puede esperar. Busca el apoyo que mereces.",
        "La intensidad de tus emociones hoy es una señal de que necesitas descanso y apoyo.",
        "No estás solo/a, aunque así se sienta ahora. Hay personas que pueden ayudarte.",
        "Lo que sientes hoy es demasiado intenso para cargarlo solo/a. Compártelo.",
        "Hoy más que nunca necesitas y mereces apoyo. No dudes en buscarlo.",
        "La intensidad emocional que atraviesas requiere gentileza hacia ti mismo/a, no crítica.",
        "No tienes que superar esto de golpe. Un paso a la vez, con apoyo.",
        "Lo que sientes con esta intensidad merece ser escuchado por alguien de confianza.",
        "Hoy es el día para poner tu bienestar por encima de cualquier otra obligación.",
        "La intensidad de lo que sientes hoy es una llamada a buscar apoyo sin demora.",
        "No tienes que aguantar esto solo/a. Hay personas y recursos disponibles para ti.",
        "Lo que sientes hoy es muy intenso y muy real. Mereces apoyo real también.",
        "Hoy no es el momento para ser valiente en silencio. Es el momento para pedir ayuda.",
        "La intensidad emocional que experimentas hoy requiere atención y cuidado especial.",
        "No tienes que estar bien para pedir ayuda. De hecho, es cuando más la necesitas.",
        "Lo que sientes con tanta fuerza hoy merece ser atendido con urgencia y cuidado.",
        "Hoy tu tarea es cuidarte y buscar apoyo. Lo demás puede esperar.",
        "La intensidad de tus emociones hoy es una señal de que mereces apoyo ahora.",
        "No estás solo/a en esto. Hay personas dispuestas a acompañarte en este momento difícil.",
    ],

    # ── Emociones críticas — bajo ────────────────────────────
    "critica_bajo": [
        "Hoy parece un día especialmente difícil. Recuerda que no tienes que enfrentarlo solo/a.",
        "Cuando todo se siente pesado, incluso respirar es un logro. Date ese crédito.",
        "Las emociones críticas merecen atención especial. ¿Hay alguien con quien puedas hablar hoy?",
        "No estás obligado/a a estar bien. Pero sí mereces apoyo. No dudes en buscarlo.",
        "Hoy puede ser un día muy difícil. Eso hace que el autocuidado sea más importante que nunca.",
        "Lo que sientes hoy, aunque difícil, merece ser escuchado con compasión.",
        "No tienes que atravesar este día solo/a. Hay personas dispuestas a ayudarte.",
        "Un día crítico es una señal de que necesitas y mereces apoyo. Búscalo.",
        "Lo que estás viviendo hoy es difícil. No lo minimices ni lo enfrentes sin apoyo.",
        "Hoy más que nunca, cuidarte es la tarea más importante. Todo lo demás puede esperar.",
        "Las emociones que sientes hoy son muy difíciles. Mereces apoyo para atravesarlas.",
        "No tienes que ser valiente en silencio. Hoy puedes pedir ayuda sin vergüenza.",
        "Lo que sientes hoy merece atención real, no solo palabras de aliento.",
        "Hoy es un día para buscar apoyo, no para intentar resolverlo todo solo/a.",
        "Las emociones críticas que experimentas hoy son una señal de que mereces cuidado especial.",
        "No estás solo/a, aunque así se sienta. Hay personas que pueden acompañarte hoy.",
        "Lo que sientes hoy es válido y requiere atención. No lo dejes para después.",
        "Hoy puede ser difícil, pero no tienes que enfrentarlo sin apoyo.",
        "Las emociones difíciles que sientes hoy merecen ser compartidas con alguien de confianza.",
        "No tienes que poder con todo hoy. Está bien pedir ayuda cuando la necesitas.",
        "Lo que atraviesas hoy es serio y merece ser tratado con seriedad y cuidado.",
        "Hoy es el día para priorizar tu bienestar por encima de cualquier otra cosa.",
        "Las emociones que sientes hoy son una señal de que mereces y necesitas apoyo.",
        "No tienes que resolver esto solo/a. Pedir ayuda es la decisión más sabia.",
        "Lo que sientes hoy merece atención y cuidado, no ignorarse ni minimizarse.",
        "Hoy puedes ser vulnerable sin avergonzarte. La vulnerabilidad también es fortaleza.",
        "Las emociones críticas que experimentas hoy son una invitación a buscar apoyo.",
        "No estás obligado/a a cargar esto solo/a. Hay personas dispuestas a ayudarte.",
        "Lo que sientes hoy es difícil, y está bien reconocerlo y buscar ayuda.",
        "Hoy tu bienestar es lo primero. No hay nada más urgente que cuidarte.",
        "Las emociones que atraviesas hoy merecen apoyo real, no solo resistencia.",
        "No tienes que aguantar esto solo/a. Busca a alguien de confianza hoy.",
        "Lo que sientes hoy es una señal de que mereces y necesitas apoyo ahora.",
        "Hoy es el día para dejar de cargar esto solo/a y buscar el apoyo que mereces.",
        "Las emociones críticas que sientes son válidas y merecen atención especializada si es necesario.",
        "No tienes que estar bien para merecer apoyo. Precisamente ahora es cuando más lo necesitas.",
        "Lo que traversas hoy es difícil. No lo hagas más difícil intentando hacerlo solo/a.",
        "Hoy puedes pedir ayuda sin justificarte. Tu bienestar no necesita justificación.",
        "Las emociones que experimentas hoy son una señal de que mereces cuidado y apoyo.",
        "No estás solo/a en esto, aunque así se sienta. Hay personas que pueden ayudarte.",
        "Lo que sientes hoy merece ser atendido con urgencia y compasión.",
        "Hoy más que nunca, buscar apoyo es el acto más valiente que puedes hacer.",
        "Las emociones críticas que sientes hoy son reales y merecen atención real.",
        "No tienes que resolver esto antes de pedir ayuda. Pide ayuda ahora.",
        "Lo que atraviesas hoy es serio. Tómatelo en serio y busca el apoyo que mereces.",
        "Hoy es el día para ser gentil contigo mismo/a y buscar el apoyo que necesitas.",
        "Las emociones que sientes hoy merecen ser escuchadas por alguien capacitado.",
        "No tienes que cargar esto en silencio. Hablar de ello ya es dar un paso importante.",
        "Lo que sientes hoy es difícil, y eso hace que el apoyo sea más necesario que nunca.",
        "Hoy tu tarea más importante es cuidarte y buscar apoyo. Empieza por ahí.",
    ],

    # ── Emociones críticas — medio ───────────────────────────
    "critica_medio": [
        "Lo que sientes hoy es válido y merece atención. No lo minimices ni lo enfrentes solo/a.",
        "Hablar con alguien de confianza puede cambiar mucho cómo te sientes. Te lo mereces.",
        "Tu bienestar es lo primero. Si sientes que necesitas apoyo, es una buena señal escucharte.",
        "Días así exigen cuidado extra. ¿Qué pequeña cosa puedes hacer hoy para cuidarte?",
        "Lo que sientes con esta intensidad merece ser atendido con seriedad y compasión.",
        "No tienes que atravesar esto solo/a. Hay personas dispuestas a acompañarte.",
        "Lo que experimentas hoy es serio y merece apoyo real, no solo resistencia.",
        "Hoy es el día para priorizar tu bienestar sin culpa ni justificación.",
        "Las emociones críticas que sientes merecen atención especializada si las necesitas.",
        "No estás obligado/a a poder con todo. Hoy está bien pedir ayuda.",
        "Lo que sientes hoy con esta intensidad es una señal de que mereces apoyo urgente.",
        "Hoy más que nunca, cuidarte es la prioridad. Las demás tareas pueden esperar.",
        "Las emociones que atraviesas hoy son difíciles y merecen ser compartidas.",
        "No tienes que ser fuerte hoy. Puedes ser honesto/a sobre lo que necesitas.",
        "Lo que sientes hoy merece atención real y apoyo real. Búscalo.",
        "Hoy es el día para dejar de cargar esto solo/a y pedir el apoyo que mereces.",
        "Las emociones críticas que experimentas son una invitación a buscar ayuda ahora.",
        "No tienes que resolver esto en silencio. Hablar de ello ya es un gran paso.",
        "Lo que sientes hoy es demasiado importante para ignorarlo o posponerlo.",
        "Hoy tu bienestar merece toda tu atención y toda la ayuda que puedas conseguir.",
        "Las emociones que sientes con esta intensidad son una señal de que necesitas apoyo.",
        "No estás solo/a aunque así se sienta. Hay personas que pueden ayudarte hoy.",
        "Lo que atraviesas hoy merece ser tratado con urgencia y cuidado.",
        "Hoy es el momento de pedir ayuda, no de aguantar en silencio.",
        "Las emociones críticas que sientes hoy son reales y requieren atención real.",
        "No tienes que superar esto solo/a. Pedir apoyo es lo más inteligente ahora.",
        "Lo que sientes hoy con esta intensidad merece ser escuchado por alguien de confianza.",
        "Hoy más que nunca, tu bienestar no puede esperar. Actúa para cuidarte.",
        "Las emociones que experimentas hoy son una señal de que mereces apoyo especializado.",
        "No tienes que estar bien para buscar ayuda. Es exactamente cuando no estás bien que más la necesitas.",
        "Lo que sientes hoy es difícil e importante. Tómatelo en serio.",
        "Hoy es el día para bajar la guardia y dejar que alguien te ayude de verdad.",
        "Las emociones críticas que atraviesas hoy merecen apoyo profesional si lo necesitas.",
        "No estás obligado/a a cargar esto. Hay personas capacitadas para ayudarte.",
        "Lo que sientes hoy merece atención inmediata y cuidado genuino.",
        "Hoy tu tarea más urgente es buscar apoyo. Todo lo demás puede esperar.",
        "Las emociones que sientes con esta intensidad son una llamada a buscar ayuda.",
        "No tienes que resolverlo todo hoy. Solo necesitas dar el primer paso hacia el apoyo.",
        "Lo que atraviesas hoy es serio y merece ser atendido con seriedad.",
        "Hoy es el momento de priorizar tu bienestar por encima de cualquier otra cosa.",
        "Las emociones críticas que experimentas son válidas y merecen atención especial.",
        "No tienes que cargar esto en silencio. Hablar ya cambia las cosas.",
        "Lo que sientes hoy con esta fuerza merece ser compartido con alguien de confianza.",
        "Hoy más que nunca, buscar apoyo es el acto más valiente e inteligente que puedes hacer.",
        "Las emociones que sientes hoy son una señal de que mereces y necesitas ayuda ahora.",
        "No estás solo/a en esto. Hay personas y recursos disponibles para acompañarte.",
        "Lo que atraviesas hoy es difícil. No lo hagas más difícil intentando hacerlo sin apoyo.",
        "Hoy es el día para ser honesto/a sobre lo que necesitas y buscarlo sin vergüenza.",
        "Las emociones críticas que sientes hoy requieren atención y cuidado especial.",
        "No tienes que aguantar esto. Mereces apoyo, y buscarlo es lo más valiente que puedes hacer.",
    ],

    # ── Emociones críticas — alto ────────────────────────────
    "critica_alto": [
        "Lo que sientes hoy es muy intenso. Por favor, no lo cargues solo/a.",
        "Tu bienestar importa. Si te sientes cómodo/a, hablar con un orientador puede ayudarte mucho.",
        "Mereces apoyo profesional si lo necesitas. Pedirlo es una señal de fortaleza, no de debilidad.",
        "Hoy es un día difícil. Recuerda que hay personas y recursos disponibles para acompañarte.",
        "La intensidad de lo que sientes hoy requiere apoyo urgente. No lo postergues.",
        "No tienes que cargar esto en silencio. Hablar con alguien puede cambiarlo todo.",
        "Lo que sientes con esta intensidad es una señal clara de que mereces ayuda ahora.",
        "Hoy más que nunca, buscar apoyo profesional es la decisión más valiente e importante.",
        "La intensidad emocional que atraviesas hoy requiere atención especializada.",
        "No estás solo/a. Hay personas capacitadas para acompañarte en este momento.",
        "Lo que sientes hoy es muy difícil y muy real. Mereces apoyo real y urgente.",
        "Hoy es el momento de buscar ayuda sin demora. Tu bienestar no puede esperar.",
        "La intensidad de tus emociones hoy es una señal de que mereces apoyo profesional.",
        "No tienes que poder con esto solo/a. Nadie debería tener que hacerlo.",
        "Lo que experimentas hoy con esta intensidad merece atención especializada inmediata.",
        "Hoy tu tarea más urgente e importante es buscar apoyo. Empieza ahora.",
        "La intensidad emocional que sientes hoy es muy alta. Por favor, no la enfrentes solo/a.",
        "No estás obligado/a a aguantar esto. Mereces ayuda y hay personas dispuestas a dártela.",
        "Lo que sientes hoy con tanta fuerza requiere apoyo urgente y especializado.",
        "Hoy más que nunca, pedir ayuda es el acto más valiente que puedes realizar.",
        "La intensidad de lo que atraviesas hoy es una llamada urgente a buscar apoyo.",
        "No tienes que ser fuerte en silencio. Hoy puedes y debes pedir ayuda.",
        "Lo que sientes hoy es demasiado intenso para enfrentarlo sin apoyo. Búscalo hoy.",
        "Hoy es el día para dar el paso más importante: buscar el apoyo que mereces.",
        "La intensidad emocional que experimentas hoy requiere atención inmediata y cuidado real.",
        "No estás solo/a en esto, aunque así se sienta. Hay personas que pueden ayudarte ahora.",
        "Lo que atraviesas hoy con esta intensidad merece apoyo profesional sin demora.",
        "Hoy tu bienestar es una emergencia. Trátalo como tal y busca ayuda.",
        "La intensidad de tus emociones hoy es una señal de que mereces apoyo urgente.",
        "No tienes que resolver esto solo/a. Pedir ayuda es la decisión más sabia ahora.",
        "Lo que sientes hoy con tanta fuerza merece ser atendido con urgencia y compasión.",
        "Hoy más que nunca, tu bienestar es lo único que importa. Cuídalo buscando apoyo.",
        "La intensidad emocional que atraviesas hoy requiere que busques apoyo sin demora.",
        "No estás obligado/a a cargar esto. Hay recursos y personas disponibles para ti ahora.",
        "Lo que sientes hoy es muy intenso y muy serio. Por favor, busca apoyo hoy.",
        "Hoy es el momento de dejar de cargar esto solo/a y buscar el apoyo que mereces.",
        "La intensidad de lo que sientes hoy es una señal de que mereces atención especializada.",
        "No tienes que aguantar esto en silencio. Hablar es el primer paso más importante.",
        "Lo que atraviesas hoy con esta intensidad requiere apoyo real y urgente.",
        "Hoy tu tarea más importante es cuidarte y buscar ayuda. Nada más es más urgente.",
        "La intensidad emocional que experimentas hoy merece ser tratada con toda la seriedad.",
        "No estás solo/a. Hay personas capacitadas y dispuestas a acompañarte en este momento.",
        "Lo que sientes hoy es demasiado intenso para ignorarlo. Por favor, busca apoyo hoy.",
        "Hoy más que nunca, buscar apoyo profesional es el acto más valiente e inteligente.",
        "La intensidad de tus emociones hoy es una llamada urgente a buscar ayuda especializada.",
        "No tienes que poder con todo. Hoy está bien, y es necesario, pedir ayuda.",
        "Lo que sientes hoy con tanta intensidad merece atención especializada inmediata.",
        "Hoy es el día para ser completamente honesto/a sobre lo que necesitas y buscarlo.",
        "La intensidad emocional que atraviesas hoy requiere que no te quedes solo/a con ella.",
        "No estás obligado/a a cargar esto solo/a. Mereces apoyo ahora. Búscalo.",
    ],

    # ── Rachas prolongadas ───────────────────────────────────
    "racha_suave": [
        "Llevas varios días con emociones difíciles. ¿Has podido hablar con alguien sobre cómo te sientes?",
        "Varios días seguidos con emociones pesadas merecen atención. No tienes que atravesarlos solo/a.",
        "Cuando las emociones difíciles se acumulan, buscar apoyo marca la diferencia.",
        "Tu constancia al registrar tus emociones muestra valentía. Ahora date también el permiso de pedir ayuda.",
        "Llevas varios días sintiéndote así. Es una señal de que algo merece atención y cuidado.",
        "Varios días con emociones difíciles son una invitación a buscar apoyo y descanso.",
        "Tu bienestar durante varios días seguidos merece ser tomado en serio.",
        "Llevas varios días con emociones pesadas. ¿Qué podrías hacer hoy para cuidarte un poco más?",
        "Varios días difíciles seguidos son una señal de que mereces apoyo adicional.",
        "Tu registro emocional de estos días muestra algo importante. Escúchalo.",
        "Llevas varios días atravesando emociones difíciles. No tienes que hacerlo solo/a.",
        "Varios días seguidos con este estado emocional merecen atención y cuidado especial.",
        "Tu bienestar durante estos días importa. ¿Has podido hablar con alguien?",
        "Llevas varios días con emociones que pesan. Es el momento de buscar apoyo.",
        "Varios días difíciles seguidos son una señal de que algo necesita cambiar.",
        "Tu constancia al registrar tus emociones es valiosa. Ahora usa esa información para buscar apoyo.",
        "Llevas varios días sintiéndote así. Eso merece atención, no ignorarse.",
        "Varios días con emociones difíciles son una invitación a buscar ayuda y cuidado.",
        "Tu bienestar de estos días es una prioridad. ¿Qué apoyo puedes buscar hoy?",
        "Llevas varios días con emociones pesadas. No las cargues en silencio.",
        "Varios días seguidos así son una señal de que mereces y necesitas apoyo.",
        "Tu registro de estos días muestra que algo merece atención real.",
        "Llevas varios días con emociones difíciles. Es el momento de no hacerlo solo/a.",
        "Varios días con este estado emocional merecen más que resistencia. Merecen apoyo.",
        "Tu bienestar durante estos días importa mucho. Busca el apoyo que mereces.",
        "Llevas varios días atravesando emociones difíciles. ¿Hay alguien con quien puedas hablar?",
        "Varios días seguidos con emociones pesadas son una señal clara de que mereces ayuda.",
        "Tu constancia al registrar es valiosa. Ahora usa esa valentía para buscar apoyo.",
        "Llevas varios días sintiéndote así. Eso no tiene que seguir siendo tu carga sola.",
        "Varios días difíciles seguidos merecen ser tomados en serio. Busca apoyo hoy.",
        "Tu bienestar de estos días merece atención real y cuidado genuino.",
        "Llevas varios días con emociones que pesan. No las enfrentes sin apoyo.",
        "Varios días con este estado emocional son una invitación urgente a buscar ayuda.",
        "Tu registro emocional de estos días es importante. Úsalo para buscar el apoyo que necesitas.",
        "Llevas varios días difíciles. Es el momento de dar el paso y buscar apoyo.",
        "Varios días seguidos con emociones difíciles son una señal de que algo necesita atención.",
        "Tu bienestar durante varios días seguidos es una prioridad que no puede ignorarse.",
        "Llevas varios días atravesando esto. No tienes que seguir haciéndolo solo/a.",
        "Varios días con emociones pesadas merecen más que seguir adelante. Merecen cuidado.",
        "Tu constancia al registrar tus emociones es valentía. Ahora úsala para pedir ayuda.",
        "Llevas varios días sintiéndote así. Eso es una señal de que mereces apoyo ahora.",
        "Varios días seguidos con este estado son una invitación a buscar ayuda y descanso.",
        "Tu bienestar de estos días importa más de lo que crees. Búscale atención.",
        "Llevas varios días con emociones difíciles. ¿Qué pequeño paso puedes dar hoy hacia el apoyo?",
        "Varios días difíciles seguidos son una señal de que algo importante necesita atención.",
        "Tu registro de estos días muestra algo que no debe ignorarse. Tómatelo en serio.",
        "Llevas varios días atravesando emociones pesadas. Busca a alguien con quien hablar hoy.",
        "Varios días con este estado emocional merecen atención especializada si la necesitas.",
        "Tu bienestar durante estos días es una prioridad. No la postergues más.",
        "Llevas varios días con emociones difíciles. Es el momento de buscar el apoyo que mereces.",
    ],

    "racha_moderada": [
        "Llevas casi una semana con emociones difíciles. Hablar con alguien de confianza puede ayudarte mucho.",
        "Varios días seguidos sintiéndote así merece que te cuides extra. ¿Hay alguien a quien puedas acudir?",
        "No estás solo/a en esto. Un orientador, amigo o familiar puede ser un gran apoyo ahora.",
        "Tu bienestar es importante. Si te sientes cómodo/a, considera buscar apoyo esta semana.",
        "Llevas cerca de una semana con emociones pesadas. Es el momento de buscar apoyo real.",
        "Casi una semana con emociones difíciles es una señal importante. No la ignores.",
        "Tu bienestar durante tantos días seguidos merece atención especializada.",
        "Llevas varios días así. Es el momento de dar el paso hacia el apoyo que mereces.",
        "Casi una semana con emociones difíciles merece más que resistir. Merece ayuda.",
        "Tu constancia al registrar tus emociones durante estos días es valiosa. Ahora busca apoyo.",
        "Llevas cerca de una semana atravesando esto. No lo hagas solo/a por más tiempo.",
        "Varios días seguidos con emociones pesadas son una señal de que algo necesita cambiar.",
        "Tu bienestar durante casi una semana seguida merece atención urgente.",
        "Llevas muchos días con emociones difíciles. Es el momento de buscar apoyo sin demora.",
        "Casi una semana con este estado emocional es una señal de que mereces ayuda real.",
        "Tu registro de estos días muestra algo importante. Úsalo para buscar el apoyo que necesitas.",
        "Llevas casi una semana atravesando emociones difíciles. No lo enfrentes sin apoyo.",
        "Varios días seguidos con emociones pesadas merecen apoyo profesional si es necesario.",
        "Tu bienestar durante estos días es una prioridad urgente. Búscale atención ahora.",
        "Llevas cerca de una semana con emociones difíciles. Es el momento de pedir ayuda.",
        "Casi una semana así es una señal de que algo importante merece atención especializada.",
        "Tu constancia al registrar es valiosa. Ahora usa esa valentía para buscar ayuda real.",
        "Llevas muchos días con emociones que pesan. No tienes que seguir cargándolas solo/a.",
        "Varios días seguidos con este estado son una invitación urgente a buscar apoyo.",
        "Tu bienestar durante casi una semana seguida merece ser tratado con toda la seriedad.",
        "Llevas casi una semana atravesando emociones difíciles. Busca apoyo hoy.",
        "Casi una semana con emociones pesadas es una señal clara de que mereces ayuda.",
        "Tu registro emocional de estos días habla. Escúchalo y busca el apoyo que necesitas.",
        "Llevas muchos días sintiéndote así. Es el momento de no hacerlo solo/a.",
        "Varios días seguidos con emociones difíciles requieren apoyo real y urgente.",
        "Tu bienestar durante casi una semana seguida es una prioridad que no puede ignorarse.",
        "Llevas cerca de una semana con emociones que pesan. Busca a alguien con quien hablar.",
        "Casi una semana con este estado emocional merece atención especializada.",
        "Tu constancia al registrar tus emociones muestra valentía. Ahora da el paso hacia el apoyo.",
        "Llevas muchos días atravesando emociones difíciles. No lo hagas sin apoyo.",
        "Varios días seguidos con emociones pesadas son una señal de que algo necesita cambiar.",
        "Tu bienestar durante casi una semana merece más que resistencia. Merece ayuda real.",
        "Llevas casi una semana con emociones difíciles. Es el momento de buscar apoyo urgente.",
        "Casi una semana así es una señal importante. Tómatela en serio y busca ayuda.",
        "Tu registro de estos días es valioso. Úsalo para dar el paso hacia el apoyo que mereces.",
        "Llevas muchos días con emociones que pesan. No tienen que seguir siendo tu carga sola.",
        "Varios días seguidos con este estado emocional requieren atención especializada.",
        "Tu bienestar durante casi una semana seguida merece apoyo profesional si lo necesitas.",
        "Llevas cerca de una semana atravesando esto. Es el momento de buscar ayuda sin demora.",
        "Casi una semana con emociones difíciles es una señal de que mereces apoyo urgente.",
        "Tu constancia al registrar durante estos días muestra que algo importante está pasando.",
        "Llevas muchos días sintiéndote así. Busca apoyo hoy. No lo postergues más.",
        "Varios días seguidos con emociones pesadas merecen atención urgente y cuidado real.",
        "Tu bienestar durante casi una semana es una prioridad urgente. Actúa ahora.",
        "Llevas casi una semana con emociones difíciles. El apoyo que mereces está disponible.",
    ],

    "racha_critica": [
        "Llevas una semana con emociones muy difíciles. Te invitamos, si te sientes cómodo/a, a hablar con un especialista de bienestar.",
        "No tienes que cargar esto solo/a por más tiempo. Hay personas capacitadas para acompañarte.",
        "Una semana es mucho tiempo cargando emociones intensas. Buscar apoyo profesional es un acto de cuidado hacia ti.",
        "Tu bienestar es lo más importante. Si puedes, habla hoy con un orientador o alguien de confianza.",
        "Llevas una semana con emociones muy difíciles. Es el momento de buscar apoyo profesional urgente.",
        "Una semana de emociones intensas es una señal de que mereces y necesitas apoyo especializado.",
        "Tu bienestar durante esta semana merece atención profesional. Búscala hoy.",
        "Llevas siete días atravesando emociones muy difíciles. No lo hagas sin apoyo profesional.",
        "Una semana con emociones tan intensas requiere atención especializada. Búscala.",
        "Tu registro de esta semana muestra algo serio. Por favor, busca apoyo profesional.",
        "Llevas una semana con emociones muy difíciles. Es urgente que busques apoyo especializado.",
        "Una semana entera con este estado emocional merece atención profesional inmediata.",
        "Tu bienestar durante esta semana es una emergencia. Trátala como tal.",
        "Llevas siete días así. Es el momento de buscar apoyo profesional sin demora.",
        "Una semana de emociones muy intensas es una señal clara de que mereces ayuda especializada.",
        "Tu registro de esta semana habla. Por favor, escúchalo y busca apoyo profesional.",
        "Llevas una semana con emociones muy difíciles. No tienes que seguir cargándolas solo/a.",
        "Una semana con este estado emocional requiere atención profesional urgente.",
        "Tu bienestar durante toda esta semana merece apoyo real y especializado.",
        "Llevas siete días atravesando emociones muy intensas. Busca apoyo profesional hoy.",
        "Una semana de emociones muy difíciles es una señal de que algo importante necesita atención.",
        "Tu constancia al registrar durante esta semana es valiosa. Úsala para buscar ayuda especializada.",
        "Llevas una semana con emociones muy difíciles. Es el momento de dar el paso hacia el apoyo.",
        "Una semana entera con emociones tan intensas merece atención profesional inmediata.",
        "Tu bienestar durante esta semana es una prioridad urgente. No lo postergues más.",
        "Llevas siete días con emociones muy difíciles. Por favor, busca apoyo especializado hoy.",
        "Una semana de emociones muy intensas requiere que no sigas enfrentándolas solo/a.",
        "Tu registro de esta semana muestra que algo serio merece atención profesional.",
        "Llevas una semana atravesando emociones muy difíciles. Busca apoyo ahora.",
        "Una semana con este estado emocional es una señal urgente de que mereces ayuda.",
        "Tu bienestar durante toda esta semana merece atención profesional urgente.",
        "Llevas siete días con emociones muy intensas. Es el momento de buscar ayuda especializada.",
        "Una semana de emociones muy difíciles merece apoyo profesional sin demora.",
        "Tu constancia al registrar esta semana muestra valentía. Úsala para pedir ayuda especializada.",
        "Llevas una semana con emociones muy difíciles. No tienes que seguir haciéndolo solo/a.",
        "Una semana entera con este estado emocional requiere atención especializada urgente.",
        "Tu bienestar durante esta semana no puede ignorarse. Busca apoyo profesional hoy.",
        "Llevas siete días atravesando emociones muy intensas. Por favor, busca ayuda especializada.",
        "Una semana de emociones muy difíciles es una señal de que mereces apoyo profesional ahora.",
        "Tu registro de esta semana es importante. Úsalo para dar el paso hacia la ayuda que mereces.",
        "Llevas una semana con emociones muy difíciles. Es urgente que busques apoyo especializado.",
        "Una semana con emociones tan intensas requiere atención profesional. No lo postergues.",
        "Tu bienestar durante esta semana merece ser tratado con toda la seriedad y urgencia.",
        "Llevas siete días con emociones muy difíciles. Hay personas capacitadas para ayudarte.",
        "Una semana entera de emociones muy intensas merece apoyo profesional inmediato.",
        "Tu constancia al registrar durante esta semana muestra algo importante. Escúchalo.",
        "Llevas una semana con emociones muy difíciles. El apoyo que mereces está disponible.",
        "Una semana de emociones muy intensas es una señal clara de que mereces ayuda especializada.",
        "Tu bienestar durante toda esta semana es una prioridad urgente. Busca apoyo hoy.",
        "Llevas siete días atravesando emociones muy difíciles. Por favor, no lo hagas solo/a.",
    ],
}