# hechos/hechos_frase.py

from experta import Fact, Field
 
 
# ─────────────────────────────────────────────────────────────
# Hechos de entrada
# ─────────────────────────────────────────────────────────────
 
class EstadoEmocional(Fact):
    clasificacion = Field(str, mandatory=True)   # positiva | neutra | negativa
    nivel         = Field(str, mandatory=True)   # bajo | medio | alto
 
 
# ─────────────────────────────────────────────────────────────
# Hechos derivados (declarados por el motor)
# ─────────────────────────────────────────────────────────────
 
class TipoFrase(Fact):
    tipo = Field(str, mandatory=True)   # clave del pool en FRASES


# ─────────────────────────────────────────────────────────────
# Base de conocimiento — pools de frases por tipo
# ─────────────────────────────────────────────────────────────

FRASES: dict[str, list[str]] = {

    # ── Emociones positivas — bajo ───────────────────────────
    "positiva_bajo": [
        "Incluso los momentos tranquilos tienen su valor. Hoy es un buen día para avanzar paso a paso.",
        "La alegría suave también es alegría. Aprovecha esta calma para enfocarte en lo que importa.",
        "Un estado positivo, aunque discreto, es el terreno ideal para aprender algo nuevo hoy.",
        "No hace falta estar eufórico para tener un gran día. Pequeños pasos cuentan.",
        "La tranquilidad que sientes hoy es una base sólida para construir algo valioso.",
        "Los días suaves también dejan huella. Aprovecha este momento para consolidar lo aprendido.",
        "Una chispa pequeña también puede encender algo grande. Hoy es un buen comienzo.",
        "Sentirte levemente bien ya es una victoria. No subestimes lo que puedes lograr desde aquí.",
        "La calma positiva es el punto ideal para tomar decisiones con claridad y sin prisa.",
        "No todos los días brillan igual, pero todos pueden avanzar. Hoy tienes el terreno a tu favor.",
        "Un estado de ánimo tranquilo y positivo es ideal para enfocarse en lo que realmente importa.",
        "Hoy no necesitas fuegos artificiales para avanzar. La constancia silenciosa también construye.",
        "Sentirte bien de manera discreta es igualmente valioso. Honra ese estado.",
        "La paz que sientes hoy es una invitación a reflexionar y agradecer lo que tienes.",
        "Incluso una leve sensación de bienestar puede ser el impulso que necesitas para dar el siguiente paso.",
        "Los momentos de calma positiva son perfectos para organizar tus ideas y prioridades.",
        "Hoy tu energía es suave pero real. Úsala con intención.",
        "No subestimes los días tranquilos. En ellos se fragua la constancia.",
        "Una actitud positiva discreta es más poderosa de lo que parece. Hoy lo tienes.",
        "Desde la calma también se avanza. A veces el camino más suave es el más efectivo.",
        "Hoy es un buen día para retomar algo pendiente con paciencia y enfoque.",
        "La alegría tranquila que sientes es una señal de que estás en equilibrio. Cuídala.",
        "Pequeñas dosis de bienestar, vividas con consciencia, suman más de lo que imaginas.",
        "Tu estado hoy es una invitación a avanzar sin presión. Aprovecha esa libertad.",
        "Sentirte levemente positivo/a es suficiente para hacer algo significativo hoy.",
        "La calma que acompaña tu bienestar de hoy es un recurso. No lo desperdicies.",
        "Hoy no tienes que conquistar el mundo. Con avanzar un poco ya es suficiente.",
        "Un estado suavemente positivo es el entorno perfecto para aprender algo nuevo.",
        "La tranquilidad positiva que sientes te permite ver con claridad lo que más importa.",
        "Hoy tu mente está en un buen lugar. Aprovecha esa claridad para algo que te sume.",
        "No hace falta una tormenta de emociones para vivir un día significativo. La calma también lo es.",
        "Tu bienestar de hoy, aunque discreto, merece ser reconocido y celebrado.",
        "Los días tranquilos son los que construyen la base de los grandes logros.",
        "Sentirte bien sin necesitar demostrarlo es una señal de madurez emocional.",
        "Hoy puedes avanzar a tu propio ritmo. No hay prisa, pero sí hay dirección.",
        "La levedad que sientes hoy es un regalo. Úsala para hacer algo que disfrutes.",
        "Un estado positivo suave es el escenario ideal para la creatividad y la reflexión.",
        "Hoy tienes el viento a tu favor, aunque sople despacio. Es suficiente para avanzar.",
        "Sentirte tranquilo/a y bien es una victoria cotidiana. No la pases por alto.",
        "Los días de calma positiva son los que más se agradecen cuando llegan los difíciles.",
        "Tu equilibrio emocional de hoy es una plataforma sólida. Construye desde aquí.",
        "Hoy puedes hacer algo pequeño pero significativo. Eso siempre suma.",
        "La sutileza de tu bienestar de hoy no le resta valor. Todo lo contrario.",
        "Avanzar despacio también es avanzar. Hoy tienes la calma para hacerlo bien.",
        "Tu estado de ánimo hoy invita a la reflexión y al enfoque. Aprovéchalo.",
        "No todo tiene que ser intenso para ser valioso. Hoy lo suave también cuenta.",
        "Sentirte así de tranquilo/a y bien es exactamente lo que necesitas para seguir adelante.",
        "La paz interior que experimentas hoy es un activo que pocas personas tienen. Valórala.",
        "Hoy es un buen día para agradecer, enfocarse y avanzar con serenidad.",
        "Incluso desde la calma más discreta, puedes dar pasos que marquen la diferencia.",
    ],

    # ── Emociones positivas — medio ──────────────────────────
    "positiva_medio": [
        "Tu energía de hoy es un regalo. Úsala para avanzar en algo que te apasione.",
        "Cuando te sientes bien, aprender fluye con más facilidad. ¡Aprovecha el momento!",
        "Un buen estado de ánimo multiplica tu capacidad. Hoy tienes mucho por dar.",
        "Estás en un momento ideal para retomar algo pendiente con entusiasmo.",
        "Este nivel de energía es perfecto para enfrentar retos con confianza.",
        "Tu bienestar de hoy es combustible para tus metas. No lo desperdicies.",
        "Sientes equilibrio y energía. Es el momento ideal para dar ese paso que has estado posponiendo.",
        "Los días así son oportunidades disfrazadas de rutina. Aprovecha cada momento.",
        "Tu estado de ánimo hoy es un activo. Invierte esa energía en lo que realmente importa.",
        "Cuando estás bien, el mundo responde diferente. Sal a él con intención hoy.",
        "Hoy tienes la combinación perfecta de calma y energía. Úsala sabiamente.",
        "Tu bienestar de hoy es una señal de que vas por buen camino. Sigue así.",
        "Sentirte bien con esta intensidad te abre puertas. ¿Cuál quieres cruzar hoy?",
        "El entusiasmo moderado es el más sostenible. Hoy lo tienes. Aprovéchalo.",
        "Tu energía de hoy no es casualidad. Es el resultado de tu esfuerzo. Celébralo.",
        "Un buen estado de ánimo es contagioso. Comparte tu energía con quienes te rodean.",
        "Hoy estás en sintonía contigo mismo/a. Es un buen momento para tomar decisiones importantes.",
        "La energía que sientes hoy es suficiente para mover lo que necesita moverse.",
        "Sentirte así es una invitación a actuar. ¿Qué has estado postergando?",
        "Tu bienestar de hoy merece ser honrado con acciones que te acerquen a tus metas.",
        "Hoy tienes el impulso necesario para avanzar en lo que más importa.",
        "Un estado de ánimo positivo y equilibrado es el mejor aliado para aprender.",
        "Aprovecha esta energía para conectar con algo que te inspire y te mueva.",
        "Tu entusiasmo de hoy es una herramienta poderosa. Úsala con propósito.",
        "Sentirte bien a este nivel te permite dar lo mejor de ti. Hoy es ese día.",
        "La motivación que sientes hoy es real. Actúa antes de que se disipe.",
        "Hoy tu mente y tu corazón están alineados. Es el momento ideal para crear.",
        "Un buen estado emocional abre la puerta a mejores relaciones, decisiones y aprendizajes.",
        "Hoy tienes energía de sobra para enfrentar lo que se ponga en tu camino.",
        "Tu bienestar de hoy es el resultado de pequeñas decisiones correctas. Reconócelas.",
        "Sentirte así de bien es una oportunidad para ser la mejor versión de ti mismo/a.",
        "La energía positiva que traes hoy puede transformar cualquier tarea en algo significativo.",
        "Hoy estás en tu elemento. Aprovecha ese estado para avanzar con determinación.",
        "Tu motivación de hoy es un recurso valioso. Inviértela en lo que más te importa.",
        "Cuando el ánimo acompaña, los obstáculos se achican. Hoy tienes ese ánimo.",
        "Un estado positivo sostenido construye confianza. Hoy estás abonando ese terreno.",
        "Sientes bienestar y claridad. Es la combinación perfecta para tomar acción.",
        "Tu energía de hoy es más que suficiente para hacer algo memorable.",
        "Hoy puedes avanzar sin esfuerzo extra. El ánimo está de tu lado.",
        "Sentirte así te recuerda de lo que eres capaz. No lo olvides cuando vengan días difíciles.",
        "Tu estado emocional de hoy es una plataforma de lanzamiento. ¿A dónde quieres ir?",
        "La vitalidad que sientes hoy es un regalo. Compártela, exprésala, úsala.",
        "Hoy tienes todo lo necesario para dar un paso importante. No lo postergues.",
        "Un ánimo positivo y equilibrado hace que todo fluya mejor. Hoy lo tienes.",
        "Tu bienestar de hoy no es una casualidad. Es el fruto de tu cuidado personal.",
        "Sentirte bien te da perspectiva. Úsala para ver el panorama completo.",
        "Hoy es un buen día para conectar, crear, aprender y avanzar. Tienes el estado para todo.",
        "La energía que llevas hoy puede hacer que lo difícil se sienta posible.",
        "Tu entusiasmo de hoy es genuino y poderoso. No lo subestimes.",
        "Aprovecha este estado de bienestar para sembrar hábitos que quieras mantener.",
    ],

    # ── Emociones positivas — alto ───────────────────────────
    "positiva_alto": [
        "Tu energía hoy es contagiosa. Aprovéchala para avanzar en lo que más importa.",
        "Días así son para recordar. Haz algo hoy que tu yo futuro agradezca.",
        "Cuando la motivación está al máximo, los límites se vuelven invitaciones. Adelante.",
        "Este nivel de energía positiva es tuyo. Úsalo con intención y disfruta el proceso.",
        "Hoy tienes mucha fuerza. Canalízala hacia algo que te llene de orgullo.",
        "La energía bien dirigida mueve cosas grandes. ¿Qué quieres mover hoy?",
        "Este es el tipo de día que recuerdas cuando los tiempos se ponen difíciles. Vívelo bien.",
        "Tu entusiasmo de hoy puede contagiar a quienes te rodean. Comparte esa energía.",
        "Estás en un muy buen momento hoy. No te conformes con poco cuando puedes dar mucho.",
        "La energía que sientes es real y poderosa. Úsala para crear algo que valga la pena.",
        "Hoy tu potencial está al máximo. Es el momento de ir por lo que quieres.",
        "Una energía así no llega todos los días. Aprovéchala bien.",
        "Tu vitalidad hoy es notable. Dirige esa fuerza con propósito y claridad.",
        "Cuando la energía es tan alta, las posibilidades se multiplican. ¿Cuál vas a elegir?",
        "Hoy sientes que puedes con mucho, y probablemente tengas razón. Demuéstratelo.",
        "Tu estado de ánimo hoy es una ventaja. Úsala bien.",
        "La energía que sientes hoy es un motor. No dejes que se desperdicie.",
        "Días como hoy te recuerdan por qué vale la pena el esfuerzo diario. Aprovéchalo.",
        "Hoy tienes la energía para hacer lo que normalmente se siente difícil. Úsala.",
        "Tu entusiasmo de hoy merece ser encauzado hacia algo significativo.",
        "La motivación alta es un estado valioso. Actúa mientras la tienes.",
        "Hoy puedes ser una versión muy buena de ti mismo/a. No te quedes corto/a.",
        "Con esta energía, cualquier meta se siente alcanzable. ¿Cuál vas a perseguir hoy?",
        "Tu estado emocional hoy es muy bueno. Merece acciones a su altura.",
        "La alegría que sientes es una fuerza. Dirígela hacia lo que más valoras.",
        "Hoy tienes el empuje para ir por cosas que quizás venías postergando. Ve por ello.",
        "Tu energía alta es un recurso valioso. Inviértela sabiamente.",
        "Días así no se olvidan. Haz algo hoy que valga la pena recordar.",
        "Con esta motivación, los obstáculos se convierten en escalones. Sube.",
        "Tu vitalidad de hoy es contagiosa. Compártela con quien la necesite.",
        "Hoy tienes mucha energía. Canalízala con propósito y determinación.",
        "La intensidad de tu bienestar hoy es una señal de que algo bueno es posible.",
        "No desperdicies esta energía en lo trivial. Hoy apunta a lo que realmente importa.",
        "Tu entusiasmo de hoy puede cambiar el rumbo de algo importante. Actúa.",
        "Cuando te sientes así de bien, el mundo parece más posible. Aprovecha esa perspectiva.",
        "Hoy tienes la energía para hacer, crear, conectar y avanzar. Úsala.",
        "La energía positiva que sientes es una oportunidad. No la dejes pasar sin usarla.",
        "Tu estado hoy es muy bueno. Úsalo para hacer algo que normalmente te costaría más.",
        "Días de mucha energía son días para atreverse. ¿Qué vas a atreverse a hacer hoy?",
        "Hoy tu mejor versión está disponible. Ponla en acción.",
        "Con esta energía, puedes abordar cosas grandes. No te limites.",
        "Tu motivación hoy es un regalo. Trátala como tal y no la desperdicies.",
        "Hoy todo fluye a tu favor. Aprovecha ese impulso para avanzar con decisión.",
        "La energía positiva de hoy es tuya. Nadie más puede aprovecharla por ti.",
        "Tu energía alta merece metas a la altura. ¿Cuál es la tuya hoy?",
        "Hoy sientes que puedes con mucho. Esa confianza es tu mayor fortaleza.",
        "La alegría que experimentas hoy es una de las mejores sensaciones. Vívela.",
        "Tu vitalidad de hoy habla por sí sola. Deja que tus acciones la acompañen.",
        "Una energía tan alta como la de hoy merece ser bien usada. Haz algo memorable.",
        "Hoy estás en un muy buen momento. Actúa en consecuencia.",
    ],

    # ── Emociones neutras — bajo ─────────────────────────────
    "neutra_bajo": [
        "La calma es el punto de partida ideal para aprender algo nuevo hoy.",
        "No siempre hay que sentir mucho para avanzar. La constancia supera al entusiasmo.",
        "Un día tranquilo es una oportunidad para consolidar lo que ya sabes.",
        "La neutralidad también es equilibrio. Hoy puedes avanzar sin prisa y sin pausa.",
        "No necesitas emoción desbordante para ser productivo. La calma también construye.",
        "Los días tranquilos son los que forjan el hábito. Hoy suma aunque no lo parezca.",
        "Sentirte neutro no es malo. Es un espacio limpio para decidir con cabeza fría.",
        "La ausencia de ruido emocional es un lujo. Aprovéchalo para enfocarte.",
        "Hoy puedes avanzar sin que nada te frene. A veces la calma es el mejor viento.",
        "Un estado neutro y sereno puede ser más productivo que uno lleno de distracciones.",
        "La neutralidad emocional te permite ver las cosas tal como son, sin filtros.",
        "Hoy no hay tormentas internas. Es el momento ideal para construir con paciencia.",
        "Un día sin grandes emociones también puede ser un gran día. Depende de ti.",
        "La quietud que sientes hoy es una invitación a la reflexión y al enfoque.",
        "Sentirte neutro/a es una señal de que estás en un punto de equilibrio. Cuídalo.",
        "Desde la calma discreta también se pueden hacer cosas importantes.",
        "Hoy tu mente está limpia de interferencias. Es el momento para trabajar con claridad.",
        "No todo tiene que sentirse intenso para ser valioso. La calma también construye.",
        "La tranquilidad que experimentas hoy es una plataforma sólida. Úsala.",
        "Los días neutros son los más subestimados y los más productivos.",
        "Hoy puedes avanzar sin el peso de las emociones intensas. Aprovecha esa ligereza.",
        "La serenidad discreta que sientes hoy te permite ver con claridad.",
        "Un estado neutro es el lienzo en blanco sobre el que puedes pintar lo que quieras.",
        "Hoy no tienes ni demasiado ni poco. Tienes exactamente lo que necesitas.",
        "La calma que sientes hoy es valiosa. No la interrumpas innecesariamente.",
        "Desde la neutralidad puedes elegir con libertad hacia dónde dirigir tu energía.",
        "Hoy no hay nada que te desvíe del camino. Es el momento de avanzar recto.",
        "La estabilidad emocional que sientes hoy es un activo. Aprovéchalo.",
        "Un día tranquilo es una oportunidad para hacer lo que normalmente se pospone.",
        "Sentirte neutro/a es estar en el centro del equilibrio. Desde ahí puedes ir a cualquier lugar.",
        "La calma de hoy no es vacío, es espacio. Llénalos con lo que realmente importa.",
        "Hoy tienes claridad sin ruido. Es el estado ideal para tomar buenas decisiones.",
        "La tranquilidad que experimentas hoy es suficiente para hacer algo significativo.",
        "Un estado neutro bien aprovechado puede producir resultados sorprendentes.",
        "Hoy no hay nada que te distraiga de lo esencial. Aprovecha esa claridad.",
        "La serenidad de hoy es una herramienta poderosa si sabes usarla.",
        "Desde la calma también se llega lejos. Hoy tienes esa calma.",
        "Un día sin grandes emociones es un día sin grandes distracciones. Aprovéchalo.",
        "La neutralidad emocional de hoy te da una perspectiva objetiva y valiosa.",
        "Hoy puedes avanzar sin el ruido de las emociones intensas. Eso es un regalo.",
        "La tranquilidad que sientes hoy no es ausencia de vida, es presencia plena.",
        "Sentirte neutro/a y en calma es uno de los estados más productivos que existen.",
        "Hoy tu energía está disponible y sin interferencias. Dirígela bien.",
        "La calma que traes hoy es suficiente para hacer lo que necesitas hacer.",
        "Un estado neutro y sereno es el terreno fértil para la concentración profunda.",
        "Hoy tienes equilibrio. Desde ahí puedes construir lo que quieras.",
        "La tranquilidad de hoy es una oportunidad para hacer algo con calidad y enfoque.",
        "Sentirte así de sereno/a es un estado que muchos buscan. Hoy lo tienes.",
        "La neutralidad de hoy te libera de extremos. Aprovecha esa libertad.",
        "Hoy puedes ser constante sin esfuerzo extra. La calma hace eso posible.",
    ],

    # ── Emociones neutras — medio ────────────────────────────
    "neutra_medio": [
        "Estás en un estado de equilibrio. Es un buen momento para revisar tus metas.",
        "La serenidad que sientes hoy es una buena base para tomar decisiones con claridad.",
        "Un estado neutro te permite ver las cosas con objetividad. Aprovecha esa claridad.",
        "No todo día tiene que ser intenso. Los días tranquilos construyen el hábito.",
        "Desde la neutralidad puedes observar sin juzgar. Eso es una habilidad valiosa.",
        "El equilibrio emocional que sientes hoy es una herramienta. Úsala bien.",
        "La serenidad es la plataforma perfecta para pensar con profundidad.",
        "Hoy tu mente está despejada. Es el momento para analizar y planificar.",
        "Desde la calma se ven más lejos los caminos. Tómate un momento para mirar adelante.",
        "El estado neutro es el centro del péndulo. Es desde aquí que puedes elegir hacia dónde moverte.",
        "Tu equilibrio de hoy es una señal de salud emocional. Reconócelo y celébralo.",
        "La calma que sientes no es indiferencia, es estabilidad. Hay una gran diferencia.",
        "Hoy tienes la distancia emocional necesaria para ver las cosas con perspectiva.",
        "Un estado equilibrado como el de hoy es ideal para resolver problemas con claridad.",
        "La neutralidad que experimentas te permite escuchar mejor a los demás y a ti mismo/a.",
        "Hoy puedes pensar con claridad y actuar con coherencia. Aprovecha ese estado.",
        "El equilibrio emocional es una de las habilidades más valiosas. Hoy la tienes.",
        "Desde la serenidad se toman las mejores decisiones. Hoy tienes esa serenidad.",
        "Tu estado de hoy es una ventaja. No todos logran este nivel de equilibrio.",
        "La calma que sientes hoy te permite conectar con lo que realmente importa.",
        "Un estado neutro y equilibrado es el mejor punto de partida para cualquier tarea.",
        "Hoy puedes ser objetivo/a y claro/a. Eso es más valioso de lo que parece.",
        "La estabilidad emocional de hoy es un recurso. Inviértelo en algo que sume.",
        "Sentirte en equilibrio te da una perspectiva limpia. Úsala para tomar buenas decisiones.",
        "Hoy no hay nada que distorsione tu percepción. Aprovecha esa claridad.",
        "La serenidad equilibrada que sientes hoy es perfecta para reflexionar y planificar.",
        "Tu calma de hoy es una fortaleza silenciosa. Reconócela.",
        "Desde el equilibrio puedes ver tanto las oportunidades como los riesgos con claridad.",
        "Hoy tienes una mente tranquila y dispuesta. Úsala para hacer algo que valga la pena.",
        "La neutralidad que sientes no es falta de pasión, es claridad mental. Aprovéchala.",
        "Un estado equilibrado como el de hoy facilita el aprendizaje y la concentración.",
        "Hoy puedes abordar cualquier tarea con la mente limpia y el corazón tranquilo.",
        "La calma que experimentas hoy es el estado ideal para la creatividad sostenida.",
        "Tu equilibrio emocional de hoy te permite dar lo mejor de ti sin agotarte.",
        "Sentirte así de tranquilo/a es una señal de que estás en el camino correcto.",
        "La serenidad de hoy es una plataforma sólida. Construye algo importante desde aquí.",
        "Hoy tienes equilibrio interior y claridad exterior. Es la combinación perfecta.",
        "Un estado neutro y estable como el de hoy es más valioso de lo que parece.",
        "La calma que sientes te permite escuchar tu intuición con más claridad.",
        "Hoy puedes avanzar con constancia y sin drama. Eso es poderoso.",
        "Tu estado de equilibrio hoy es una señal de madurez emocional. Recónocela.",
        "La tranquilidad que sientes te da libertad para elegir cómo reaccionar ante cada situación.",
        "Hoy tienes la calma necesaria para hacer las cosas bien, sin prisa y sin descuido.",
        "Un estado neutro equilibrado es el terreno perfecto para la concentración profunda.",
        "La serenidad que experimentas hoy es un activo. No la subestimes.",
        "Hoy puedes ser la versión más ecuánime de ti mismo/a. Aprovecha esa capacidad.",
        "Tu equilibrio de hoy te permite ver los problemas como lo que son, no como tragedias.",
        "La calma que sientes hoy es una señal de que tu trabajo interior está dando frutos.",
        "Sentirte en equilibrio es una de las mejores sensaciones posibles. Hoy la tienes.",
        "Tu estado neutro y equilibrado de hoy es el punto de partida ideal para cualquier cosa.",
    ],

    # ── Emociones neutras — alto ─────────────────────────────
    "neutra_alto": [
        "Tu calma hoy es real y valiosa. Ese equilibrio interno es una fortaleza.",
        "Sentirte estable es más de lo que parece. Desde aquí puedes construir mucho.",
        "La tranquilidad que sientes hoy es un buen punto de partida. Úsala para reflexionar.",
        "Estás centrado/a. Ese es un buen lugar desde el que avanzar hoy.",
        "Una serenidad así no siempre está disponible. Hoy la tienes. Aprovéchala.",
        "Tu equilibrio de hoy habla de trabajo interno. Eso se nota y se valora.",
        "Desde esta calma puedes tomar decisiones con más claridad.",
        "La estabilidad que sientes hoy es un recurso. No la subestimes.",
        "Una mente tranquila y clara tiene mucho poder. Hoy la tienes.",
        "Este estado de calma es un buen momento para dedicar tiempo a algo que realmente valoras.",
        "Tu serenidad de hoy es sólida. Pocos logran este nivel de equilibrio en su día a día.",
        "La tranquilidad que experimentas hoy es el resultado de un trabajo interno real.",
        "Hoy tu calma te permite abordar lo que venga con ecuanimidad.",
        "Una tranquilidad tan sostenida como la de hoy merece ser aprovechada.",
        "Tu equilibrio de hoy es notable. Úsalo para hacer algo que importa.",
        "La serenidad que sientes hoy te da claridad. Es un buen momento para usarla.",
        "Hoy tienes una calma que no siempre está disponible. Aprovéchala bien.",
        "Tu calma de hoy no es pasividad, es claridad. Dirígela con propósito.",
        "Un estado de serenidad como el de hoy es una oportunidad. Úsala.",
        "La estabilidad emocional que sientes hoy es una ventaja real.",
        "Hoy tu mente está en un estado de claridad. Úsala para lo que más importa.",
        "La calma que experimentas hoy es una buena base desde la que construir.",
        "Tu serenidad de hoy es una fortaleza. No todos llegan a este nivel de equilibrio.",
        "Desde una calma como la de hoy, todo parece más manejable.",
        "Tu estado de ecuanimidad hoy es valioso. Honralo con acciones coherentes.",
        "La tranquilidad que sientes hoy te permite ver las cosas con más claridad.",
        "Hoy tienes un nivel de equilibrio que merece ser aprovechado. Celébralo.",
        "Tu calma de hoy es una herramienta. Úsala con intención.",
        "Una serenidad como la de hoy abre espacio para hacer lo que normalmente cuesta más.",
        "Hoy tu equilibrio interior es tu mayor fortaleza. Actúa desde ese lugar.",
        "La calma que experimentas hoy es una señal de crecimiento personal real.",
        "Tu serenidad de hoy merece ser usada en algo que esté a su altura.",
        "Desde esta calma puedes hacer cosas que normalmente requieren más esfuerzo.",
        "Hoy tienes claridad interior. Úsala para tomar decisiones que importan.",
        "Tu equilibrio de hoy es una de tus fortalezas. Reconócela.",
        "La tranquilidad que sientes hoy es el estado ideal para el trabajo enfocado.",
        "Hoy tu calma es sólida. Eso te da más margen para actuar con serenidad.",
        "Una calma como la de hoy es un estado valioso. Aprovéchala.",
        "Tu serenidad de hoy te da una perspectiva más amplia de lo cotidiano.",
        "Hoy tienes una estabilidad emocional real. Úsala para algo que importe.",
        "La calma que experimentas hoy es una buena base para lo que venga.",
        "Tu calma de hoy es una señal de que has trabajado en ti mismo/a. Eso vale mucho.",
        "Desde una serenidad como la de hoy, los problemas se ven con más claridad.",
        "Hoy tu equilibrio interior es sólido. Desde ahí puedes ayudar a otros también.",
        "La tranquilidad que sientes hoy es un recurso. No la desperdicies.",
        "Tu estado de calma de hoy te permite conectar con lo que realmente importa.",
        "Una calma como la de hoy merece ser aprovechada en algo que valga la pena.",
        "Hoy tienes una serenidad que no siempre está disponible. Úsala bien.",
        "Tu equilibrio de hoy es un activo. Inviértelo en algo que importe.",
        "La calma que experimentas hoy es una señal de que estás en el camino correcto.",
    ],

    # ── Emociones negativas — bajo ───────────────────────────
    "negativa_bajo": [
        "No todos los días se sienten perfectos, y está bien. Date un momento para respirar.",
        "Las emociones difíciles también tienen algo que enseñarnos. Escúchate con amabilidad.",
        "Incluso en días grises, pequeñas acciones marcan la diferencia. Un paso es suficiente.",
        "Está bien no estar bien del todo. La autocompasión también es parte del aprendizaje.",
        "Los días difíciles también pasan. Hoy solo necesitas llegar al final del día.",
        "Sentirte así a veces es completamente normal. No te exijas más de lo que puedes dar hoy.",
        "Incluso una pequeña acción positiva puede cambiar el rumbo del día.",
        "No tienes que resolver todo hoy. A veces basta con cuidarte un poco.",
        "Los días difíciles son parte del camino, no el camino entero.",
        "Permítete sentir sin juzgarte. Las emociones son información, no debilidades.",
        "Hoy no tienes que ser tu mejor versión. Con ser tú mismo/a es suficiente.",
        "Un día difícil no define tu trayectoria. Es solo un día.",
        "Date permiso de tener un día menos brillante. No pasa nada.",
        "Las emociones difíciles son visitantes temporales. No les abras la puerta de par en par.",
        "Hoy puedes avanzar despacio. No tienes que correr.",
        "Reconocer que no te sientes bien ya es un acto de honestidad valioso.",
        "No tienes que fingir que estás bien si no lo estás. La autenticidad también es fortaleza.",
        "Un día con emociones difíciles también puede tener momentos de calma. Búscalos.",
        "Lo que sientes hoy es válido. No lo minimices ni lo exageres.",
        "Hoy puedes ser gentil contigo mismo/a. Eso también es productivo.",
        "Las emociones incómodas a veces son señales de que algo necesita atención. Escúchalas.",
        "No hace falta estar bien para hacer algo pequeño y significativo hoy.",
        "Hoy puedes darte el permiso de no rendir al cien. Mañana es otro día.",
        "Un estado emocional difícil no cancela tu valor como persona.",
        "Sentirte así hoy no significa que mañana vaya a ser igual.",
        "Las emociones difíciles son parte de la experiencia humana. No estás solo/a en esto.",
        "Hoy basta con respirar, avanzar poco a poco y llegar al final del día.",
        "No tienes que superar todo de golpe. Un paso a la vez es suficiente.",
        "Lo que sientes hoy tiene valor aunque sea incómodo. Escúchalo con curiosidad.",
        "Hoy puedes ser compasivo/a contigo mismo/a. Te lo mereces.",
        "Un día difícil es una oportunidad para practicar la resiliencia. Sin prisa.",
        "Sentirte así no es un fracaso. Es parte de ser humano/a.",
        "Hoy puedes hacer lo mínimo necesario y eso está perfectamente bien.",
        "Las emociones difíciles también pasan. Confía en eso.",
        "No tienes que estar siempre bien. Hoy puedes simplemente estar.",
        "Un estado emocional difícil es temporal. Esto también va a cambiar.",
        "Hoy puedes cuidarte sin culpa. El autocuidado no es egoísmo.",
        "Sentirte así a veces es una señal de que eres humano/a y estás vivo/a.",
        "No te juzgues por cómo te sientes hoy. Las emociones no se eligen.",
        "Hoy puedes ir despacio. La tortuga también llega a la meta.",
        "Un día difícil bien atravesado construye fortaleza. Estás haciéndolo.",
        "Lo que sientes hoy merece ser reconocido, no ignorado ni amplificado.",
        "Hoy puedes darte un descanso sin culpa. Lo necesitas y lo mereces.",
        "Las emociones difíciles a veces son el precio de estar completamente vivo/a.",
        "No tienes que solucionar hoy lo que no se rompió hoy.",
        "Sentirte así es válido. Y también es temporal. Las dos cosas son ciertas.",
        "Hoy puedes simplemente respirar y dejar que el día pase.",
        "Un estado emocional difícil no te define. Es solo cómo te sientes hoy.",
        "Lo más valiente que puedes hacer hoy es cuidarte sin juzgarte.",
        "Hoy no tienes que ser fuerte. Solo tienes que ser honesto/a contigo mismo/a.",
    ],

    # ── Emociones negativas — medio ──────────────────────────
    "negativa_medio": [
        "Sentir esto con intensidad media es una señal de que algo merece tu atención. ¿Qué necesitas hoy?",
        "No tienes que resolver todo hoy. A veces descansar ya es avanzar.",
        "Las emociones difíciles son temporales, aunque no lo parezca en el momento.",
        "Date permiso de sentir. Ignorar las emociones difíciles no las hace desaparecer.",
        "Lo que sientes hoy tiene valor. Escúchalo en lugar de huir de ello.",
        "Reconocer una emoción difícil ya es un acto de valentía. Vas bien.",
        "No tienes que estar bien para seguir adelante. Avanza a tu ritmo.",
        "Las emociones incómodas son invitaciones a mirar hacia adentro. ¿Qué te están diciendo?",
        "Hoy puede ser difícil, pero no definitivo. Mañana empieza otra oportunidad.",
        "Cada vez que te permites sentir y sigues adelante, te vuelves más fuerte.",
        "Lo que sientes hoy es importante. No lo minimices con frases de superación fácil.",
        "Permitirte sentir esto con honestidad es el primer paso para manejarlo.",
        "No tienes que disimular lo que sientes. La autenticidad también es una forma de avanzar.",
        "Lo que estás experimentando hoy merece atención y cuidado, no ignorarse.",
        "Hoy puedes hacer menos y cuidarte más. Eso también es productivo.",
        "Las emociones difíciles a esta intensidad son señales de que algo necesita espacio.",
        "No tienes que superar esto solo/a. Hay personas dispuestas a acompañarte.",
        "Lo que sientes hoy tiene peso. Reconócelo y busca la manera de aliviarlo.",
        "Hoy puedes pedir ayuda. No es señal de debilidad, es señal de inteligencia emocional.",
        "Las emociones difíciles que sientes hoy merecen ser escuchadas, no silenciadas.",
        "Hoy puede ser un día para descansar, reflexionar y darte el espacio que necesitas.",
        "Lo que sientes con esta intensidad es real y válido. No lo ignores.",
        "No tienes que fingir que estás bien cuando no lo estás. La honestidad es más sana.",
        "Hoy puedes ser compasivo/a contigo mismo/a. Te lo has ganado.",
        "Las emociones difíciles también tienen un principio y un fin. Este también pasará.",
        "No tienes que resolverlo todo hoy. A veces lo más valiente es descansar.",
        "Lo que sientes hoy merece ser atendido con cuidado y sin juicio.",
        "Hoy es un día para cuidarte, no para exigirte. Date ese permiso.",
        "Las emociones incómodas que sientes son temporales, aunque se sientan permanentes.",
        "No estás solo/a en lo que sientes. Muchas personas han estado en este lugar.",
        "Hoy puedes ir más despacio. No hay ninguna regla que diga que tienes que correr.",
        "Lo que sientes con esta intensidad merece ser expresado, no guardado.",
        "Hoy es un buen día para hablar con alguien de confianza sobre cómo te sientes.",
        "Las emociones difíciles que atraviesas hoy son parte del proceso. Confía en él.",
        "No tienes que estar en tu mejor momento para merecer cuidado y apoyo.",
        "Hoy puedes poner las metas en pausa y priorizar tu bienestar. Está bien.",
        "Lo que sientes hoy es una señal de que algo en tu vida merece atención.",
        "No tienes que superar esto de golpe. Un día a la vez es suficiente.",
        "Las emociones difíciles a esta intensidad son una invitación a buscar apoyo.",
        "Hoy puedes darte permiso de no estar bien. No tiene que haber razón suficiente.",
        "Lo que sientes merece espacio y tiempo. No te apresures a superarlo.",
        "No tienes que cargar esto solo/a. Buscar apoyo es un acto de valentía.",
        "Hoy puede ser un día difícil, pero también puede ser el día en que pidas ayuda.",
        "Las emociones difíciles que sientes hoy son reales y merecen atención real.",
        "No tienes que minimizar lo que sientes para que los demás se sientan cómodos.",
        "Hoy puedes cuidarte sin justificarte. Tu bienestar no necesita justificación.",
        "Lo que sientes con esta intensidad merece ser atendido, no ignorado.",
        "Hoy es un buen día para respirar profundo y darte el espacio que necesitas.",
        "Las emociones difíciles a veces son el cuerpo y la mente pidiendo descanso. Escúchalos.",
        "No tienes que superar todo para merecer apoyo. Solo tienes que pedirlo.",
    ],

    # ── Emociones negativas — alto ───────────────────────────
    "negativa_alto": [
        "Sentirte así de cargado/a es agotador. Mereces un momento para respirar sin exigirte nada.",
        "Lo que estás sintiendo hoy es muy real y muy pesado. No tienes que fingir que no lo es.",
        "Hay días en que simplemente todo pesa más. Hoy parece ser uno de esos. Date espacio.",
        "No estás exagerando. Lo que sientes hoy es intenso y merece ser tratado con cuidado.",
        "Qué difícil debe ser cargarlo todo sintiéndote así. Hoy puedes soltar un poco.",
        "Sentirte al límite no dice nada malo de ti. Dice que has estado cargando mucho.",
        "Es completamente válido que hoy sea un día difícil. No tienes que justificarlo.",
        "Lo que sientes hoy merece ser reconocido, no minimizado ni empujado para después.",
        "Nadie debería tener que atravesar días así sin que alguien los vea. Hoy te vemos.",
        "Estar en el límite emocionalmente es agotador. Hoy el descanso también es avanzar.",
        "No tienes que poder con todo hoy. Nadie puede, y está bien que así sea.",
        "Lo que sientes con tanta intensidad no es una debilidad. Es una señal de que algo importa.",
        "Hoy está bien no estar bien. No necesitas recuperarte rápido ni demostrarlo.",
        "Sentirte así de intenso/a merece atención y gentileza, empezando por la tuya propia.",
        "No tienes que seguir como si nada cuando por dentro todo se siente tan pesado.",
        "Es mucho lo que cargas. Hoy puedes permitirte descansar sin culpa.",
        "Lo que estás viviendo emocionalmente hoy es difícil. No tienes que enfrentarlo con prisa.",
        "Hoy no te pidas más de lo que puedes dar. Ya es suficiente con que estés aquí.",
        "Sentirte así con tanta fuerza merece que te trates con la misma compasión que le darías a alguien querido.",
        "No hace falta que te compongas rápido. Los días difíciles necesitan su tiempo.",
        "Lo que sientes hoy no te hace menos capaz. Te hace humano/a en un momento muy exigente.",
        "Hoy puedes bajar la guardia. No tienes que demostrar nada ni a nadie.",
        "Está bien si hoy solo puedes hacer lo mínimo. A veces lo mínimo es todo lo que se puede.",
        "Lo que traversas hoy es real y merece respeto, no apresuramiento.",
        "Sentirte tan cargado/a hoy es una invitación a pausar, no a esforzarte más.",
        "No tienes que superar esto más rápido de lo que puedes. Date el tiempo que necesitas.",
        "Hoy puedes ser honesto/a contigo mismo/a sobre cómo estás. Eso ya es un acto valioso.",
        "Lo que sientes hoy con tanta intensidad merece espacio, no silencio.",
        "Es válido que hoy todo se sienta demasiado. No tienes que minimizarlo para seguir.",
        "Hoy puedes pedirle a alguien cercano que simplemente esté contigo. No tienes que explicar mucho.",
        "Lo que estás sintiendo tiene sentido, aunque a veces no sepamos bien por qué.",
        "Sentirte así de intenso/a hoy no es algo que tengas que resolver de inmediato. Respira.",
        "Nadie puede estar bien todos los días. Hoy es uno de esos días, y está bien.",
        "Lo que sientes merece compasión. Empieza por dártela tú mismo/a.",
        "Hoy puede ser un día para simplemente existir sin exigencias. Te lo mereces.",
        "Sentirte en el límite es una señal de que algo necesita atención. No la ignores.",
        "Lo que traversas emocionalmente hoy es mucho. No tienes que cargarlo todo solo/a.",
        "Hoy puedes dejar ir la expectativa de estar bien. A veces solo es posible estar.",
        "Está bien que hoy sea difícil. No tienes que fingir que no lo es para seguir adelante.",
        "Lo que sientes hoy merece ser escuchado, aunque sea solo por ti mismo/a.",
        "Hoy puedes ser gentil contigo como lo serías con alguien que quieres mucho.",
        "Sentirte así de cargado/a es una razón válida para ir más despacio hoy.",
        "No tienes que tener todo bajo control para merecer un respiro. Lo mereces ahora.",
        "Lo que sientes con tanta intensidad hoy merece atención, no represión.",
        "Hoy puedes soltar la exigencia y simplemente darte lo que necesitas. Eso es suficiente.",
        "Sentirte así no es señal de que algo está mal contigo. Es señal de que algo pesa mucho.",
        "No tienes que estar bien para merecer cuidado. Precisamente hoy, que no lo estás, más lo mereces.",
        "Lo que traversas hoy es difícil de verdad. Darte cuenta de eso ya es un paso.",
        "Hoy puedes ser compasivo/a contigo mismo/a sin condiciones. Lo que sientes lo merece.",
        "Sentirte al límite hoy es suficiente razón para pausar y tratarte con mucha gentileza.",
    ],

    "negativa_critico": [
        "Lo que sientes hoy es abrumador, y eso importa. Por favor, no lo cargues solo/a.",
        "Mereces apoyo real ahora mismo. No mañana, no cuando estés listo/a. Ahora.",
        "Sabemos que todo se siente muy pesado hoy. Hay personas preparadas para acompañarte en esto.",
        "Lo que estás viviendo hoy es demasiado para cargarlo en silencio. Por favor, habla con alguien.",
        "No tienes que poder con todo esto solo/a. De verdad. Busca a alguien que pueda ayudarte hoy.",
        "Sentirte así de abrumado/a merece atención urgente. No esperes más para pedir ayuda.",
        "Lo que traversas hoy es muy serio, y lo que sientes lo confirma. Por favor, busca apoyo.",
        "Hay personas capacitadas para acompañarte exactamente en este momento. No tienes que esperar.",
        "Tu dolor hoy es real y muy válido. También merece atención profesional. Dátela.",
        "No estás exagerando. Lo que sientes hoy es una señal clara de que necesitas apoyo ya.",
        "Mereces que alguien te acompañe en esto. No tienes que atravesarlo en soledad.",
        "Sentirte así durante tanto tiempo es demasiado para cargarlo sin ayuda. Por favor, búscala.",
        "Lo que experimentas hoy no es algo que deba ignorarse. Busca apoyo hoy mismo.",
        "Nadie debería tener que sentirse así sin recibir ayuda. Tú tampoco. Pídela hoy.",
        "Lo que cargas emocionalmente hoy es demasiado pesado para cargarlo solo/a. Compártelo.",
        "Sentirte así es una señal urgente de que necesitas más apoyo del que puedes darte a ti mismo/a.",
        "Hoy más que nunca importa que no estés solo/a. Por favor, acércate a alguien.",
        "Lo que sientes hoy requiere atención real, no solo tiempo. Busca apoyo profesional.",
        "No tienes que llegar a un punto peor para merecer ayuda. La mereces exactamente ahora.",
        "Tu bienestar hoy es una prioridad que no puede esperar. Por favor, busca apoyo.",
        "Lo que estás viviendo emocionalmente hoy es muy serio. No lo enfrentes sin ayuda.",
        "Sentirte así durante días seguidos es una señal de que algo necesita atención profesional urgente.",
        "No hace falta que toques fondo para que tu dolor sea suficientemente válido. Ya lo es.",
        "Lo que traversas hoy merece apoyo real, no solo resistencia. Busca a alguien hoy.",
        "Hay personas preparadas para ayudarte a atravesar exactamente lo que sientes hoy.",
        "Tu dolor importa. Y precisamente porque importa, merece atención profesional ahora.",
        "Sentirte así de abrumado/a no es algo que tengas que superar solo/a. Pide ayuda.",
        "Lo que sientes hoy es demasiado intenso para ignorarlo. Por favor, actúa en favor de ti.",
        "No tienes que demostrar que puedes con todo. Hoy lo más valiente es pedir ayuda.",
        "Lo que experimentas hoy merece ser escuchado por alguien capacitado para acompañarte.",
        "Sentirte así durante tanto tiempo no es sostenible. Mereces apoyo real ahora.",
        "Lo que cargas hoy en silencio es demasiado. Hay personas que pueden ayudarte a soltarlo.",
        "No tienes que seguir resistiendo solo/a. Buscar ayuda hoy es la decisión más importante que puedes tomar.",
        "Lo que sientes hoy habla muy claro: necesitas y mereces apoyo profesional. No lo pospongas.",
        "Sentirte en el límite durante tanto tiempo merece atención urgente. Por favor, búscala.",
        "Tu bienestar no puede seguir esperando. Lo que sientes hoy lo confirma. Pide ayuda.",
        "Lo que atraviesas emocionalmente hoy es muy serio y muy real. Mereces apoyo a la altura.",
        "No tienes que cargar esto más tiempo. Hay personas dispuestas a acompañarte ahora mismo.",
        "Sentirte así es una señal de que algo necesita cambiar hoy. El primer paso es pedir ayuda.",
        "Lo que sientes hoy no tiene que seguir así. Hay ayuda disponible y la mereces.",
        "No dejes que el miedo o la vergüenza te impidan buscar el apoyo que claramente necesitas.",
        "Lo que experimentas hoy merece atención profesional. No mañana. Hoy.",
        "Sentirte así de abrumado/a durante tantos días es demasiado para cualquier persona sola.",
        "Tu dolor hoy es una señal de que mereces apoyo real, no solo fuerza de voluntad.",
        "No tienes que seguir así. Hay personas capacitadas para ayudarte a sentirte mejor.",
        "Lo que cargas hoy emocionalmente merece ser atendido con urgencia y con cuidado.",
        "Sentirte así no es algo que debas normalizar. Mereces apoyo profesional ahora.",
        "Lo que traversas hoy es demasiado serio para enfrentarlo sin ayuda. Por favor, búscala.",
        "No estás solo/a en esto, aunque así se sienta. Hay personas que pueden y quieren ayudarte.",
        "Hoy tu bienestar es lo más urgente que existe. Trátalo así y busca apoyo sin demora.",
    ],
}